### ISSUE TITLE
GC can lead to data loss in extreme scenarios

### ISSUE THREAD

**Issue by leoppro** [pingcap/ticdc#1048]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1.  The detail

> The following scenarios are only theoretically possible and no reproduction has been attempted.

After #1045, The CDC owner checks if the StartTS is more than GC safe point before creating the changefeed. But this kind of checking is not rigorous enough. Think about the following scenarios:

1. A user creates a changefeed with 140 as the StartTs.
2. cdc cli and the cdc owner obtain the GC safe point from PD, and the GC safe point is 100, so the check passes,  and the changefeed is created successfully.
3. Before the cdc owner could set the GC service TTL, TiDB starts the GC worker, and the GC safe point is updated to 150.
4. The cdc then creates an Eventfeed connection to TiKV with 140 as the StartTs.
5. At this moment, TiKV **does not** check if the StartTs is less then the GC safe point, and starts to scan incrementally right away.

Therefore, we got a data-loss bug without any error thrown.

2. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        master(2020.10.30)
        ```

    - TiCDC version (execute `cdc version`):

        ```
        master(2020.10.30)
        ```

**Comment by overvenus** [comment]
#736 proposes to move cli functionality to server which includes creating changefeed. So cdc server can set a GC service point before creating changfeed.

**Comment by leoppro** [comment]
fixed by #1045

**Comment by leoppro** [comment]
fixed by #1045
