### ISSUE TITLE
Add option to disable batching in Open Protocol

### ISSUE THREAD

**Issue by liuzix** [pingcap/ticdc#1054]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Separating individual records from an Open Protocol message can be complicated with Flink. It is time consuming to make each application that consumes the data parse the batch.

**Describe the feature you'd like:**

The ability to disable batching in Open Protocol.

**Describe alternatives you've considered:**

Writing a Flink Job that transforms the message stream and write it back to another topic in Kafka.

**Comment by amyangfei** [comment]
closed and create a new one
