### ISSUE TITLE
There is no nil check when the functions util.TimezoneFromCtx and util.KVStorageFromCtx are called

### ISSUE THREAD

**Issue by dengqee** [pingcap/ticdc#1102]
## Bug Report
Function **util.TimezoneFromCtx** and **util.KVStorageFromCtx** maybe return **nil**, these places don't check **nil**:

https://github.com/pingcap/ticdc/blob/388fbccf973305671a52653f5ecb19bb1982d639/cdc/owner.go#L212
https://github.com/pingcap/ticdc/blob/388fbccf973305671a52653f5ecb19bb1982d639/cdc/processor.go#L179
https://github.com/pingcap/ticdc/blob/388fbccf973305671a52653f5ecb19bb1982d639/cdc/processor.go#L963

https://github.com/pingcap/ticdc/blob/388fbccf973305671a52653f5ecb19bb1982d639/cdc/entry/mounter.go#L161
https://github.com/pingcap/ticdc/blob/388fbccf973305671a52653f5ecb19bb1982d639/cdc/sink/mysql.go#L463
https://github.com/pingcap/ticdc/blob/388fbccf973305671a52653f5ecb19bb1982d639/cdc/sink/mysql.go#L1199

**Comment by overvenus** [comment]
Indeed, perhaps we could return an error instead of failing surprisingly. Could you send a PR to fix them?

**Comment by dengqee** [comment]
> Indeed, perhaps we could return an error instead of failing surprisingly. Could you send a PR to fix them?

I will try my best to send a PR to fix them. 
Similarly，[`util.CaptureAddrFromCtx`](https://github.com/pingcap/ticdc/blob/bc6b10ee276060249616a8d7a8ce3eedaff83461/pkg/util/ctx.go#L36) and [`util.ChangefeedIDFromCtx` ](https://github.com/pingcap/ticdc/blob/bc6b10ee276060249616a8d7a8ce3eedaff83461/pkg/util/ctx.go#L109)do not return `error`, could I add it?
In the other hand, in [pkg/util/ctx_test.go](https://github.com/pingcap/ticdc/blob/master/pkg/util/ctx_test.go), there are only two functions defined by [ctx.go](https://github.com/pingcap/ticdc/blob/master/pkg/util/ctx.go) are test, i.e. `util.CaptureAddrFromCtx`, `util.ChangefeedIDFromCtx`, could I add unit tests about others functions defined by [ctx.go](https://github.com/pingcap/ticdc/blob/master/pkg/util/ctx.go)?
