### ISSUE TITLE
When Kafka uses sasl, how do I import data into Kafka using TiCDC

### ISSUE THREAD

**Issue by rjfh1980s** [pingcap/ticdc#1106]
## Using TiCDC to treat Kafka as a downstream, but Kafka uses sasl

When the TiCDC is used to import data into Kafka, the Kafka cluster starts the SASL mechanism, and the three parameters security.protocol, sasl.mechanism and sasl.jaas.config need to be configured in the TiCDC startup command.

- My command to start the TiCDC is:
> tiup cdc cli changefeed create --pd=http://192.168.88.8:2379 --sink-uri="kafka://17.1.8.2:9092/test_tidb_binlog_to_kafka?kafka-version=0.10.2.1&max-message-bytes=67108864&compressionType=LZ4" --opts security.protocol="SASL_PLAINTEXT" --opts sasl.mechanism="PLAIN" --opts sasl.jaas.config="org.apache.kafka.common.security.plain.PlainLoginModule required username='test-kafka' password='kafka-test';"

- After running the start command, the output error is:

> Error: [CDC:ErrKafkaNewSaramaProducer]kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

How do I configure the SASL parameter for TiCDC connection Kafka?

**Comment by amyangfei** [comment]
`SASL` based authentication with Kafka broker is not supported now. Welcome to submit a PR to support this feature.

**Comment by rjfh1980s** [comment]
> `SASL` based authentication with Kafka broker is not supported now. Welcome to submit a PR to support this feature.

Thanks for your reply!
