### ISSUE TITLE
maxwell protocol, nil pointer acces in delete event

### ISSUE THREAD

**Issue by xinydev** [pingcap/ticdc#1109]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

I am using ticdc to sync maxwell  message to kafka. When I delete a row in TiDB, the ticdc tool crash.  

If I change `enable-old-value = true`, the ticdc works well

2. What did you expect to see?

ticdc works well while delete record in tidb, no matter enable old value or not/ 

3. What did you see instead?

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
      
        ```
      v4.0.8
        ```

    - TiCDC version (execute `cdc version`):

        ```
         Release Version: v4.0.2-228-gd981921-dev
         Git Commit Hash: d98192198c48d66093b05feef2e4391b50dd6319
        Git Branch: master
        UTC Build Time: 2020-11-20 06:41:56
       Go Version: go version go1.15.2 linux/amd64
        ```

**Comment by leoppro** [comment]
did you enable the `old-value`?
when we using the maxwell protocol, we should enable the `old-value` at the same time.
see: https://docs.pingcap.com/zh/tidb/stable/manage-ticdc#%E8%BE%93%E5%87%BA%E8%A1%8C%E5%8F%98%E6%9B%B4%E7%9A%84%E5%8E%86%E5%8F%B2%E5%80%BC-%E4%BB%8E-v405-%E7%89%88%E6%9C%AC%E5%BC%80%E5%A7%8B%E5%BC%95%E5%85%A5

**Comment by amyangfei** [comment]
TiCDC doesn't force to enable old-value feature when protocol is maxwell. Maybe we should do the same thing as `canal`

**Comment by xinydev** [comment]
Is there any progress on this issue？  
I think it would be better to fix this problem instead of letting users do special operations

**Comment by amyangfei** [comment]
> Is there any progress on this issue？
> I think it would be better to fix this problem instead of letting users do special operations

In #1137 TiCDC will force to enable `old value` when protocol is `maxwell`, do you think it is reasonable?

**Comment by xinydev** [comment]
> > Is there any progress on this issue？
> > I think it would be better to fix this problem instead of letting users do special operations
> 
> In #1137 TiCDC will force to enable `old value` when protocol is `maxwell`, do you think it is reasonable?

Is it possible that some users do not want old values and also want to try kafka?

**Comment by amyangfei** [comment]
> > > Is there any progress on this issue？
> > > I think it would be better to fix this problem instead of letting users do special operations
> > 
> > 
> > In #1137 TiCDC will force to enable `old value` when protocol is `maxwell`, do you think it is reasonable?
> 
> Is it possible that some users do not want old values and also want to try kafka?

In this scenario we recommend using Open Protocol
