### ISSUE TITLE
KV client overhead of select and goroutine schedule is too high

### ISSUE THREAD

**Issue by overvenus** [pingcap/ticdc#1143]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

Set up a changefeed that watches about 20K regions with ~400 update workload.

TiCDC costs about 2100% CPU usage. Here is the flamegraph. It spends most CPU on select mutex and runtime schedule.

![image](https://user-images.githubusercontent.com/2150711/100603646-5f9d4d00-3340-11eb-8942-c4180a07bbba.png)

2. What did you expect to see?

It should consume a reasonable CPU, 2100% is too high. 

3. What did you see instead?

4. Versions of the cluster

master

Pprof: [pprof.cdc.samples.cpu.004.pb.gz](https://github.com/pingcap/ticdc/files/5615620/pprof.cdc.samples.cpu.004.pb.gz)

**Comment by amyangfei** [comment]
solved in #1393
