### ISSUE TITLE
--sink-uri contains special characters "#"

### ISSUE THREAD

**Issue by glkappe** [pingcap/ticdc#1145]
link: https://asktug.com/t/topic/63919
When I execute the following command to run ticdc

``` tiup cdc cli changefeed create --sink-uri=“mysql://root:1234#56@172.16.188.189:3306/” --changefeed-id=“test12-mysql” --config=/data/cdc_cfg/test.toml
```

If the password is 「1234#56」, the command will report the following error:

``` 
fail to query session variable allow_auto_random_explicit_insert: [CDC:ErrMySQLQueryError]dial tcp: lookup root on 114.114.114.114:53: no such host
Error: run /home/tidb/.tiup/components/cdc/**v4.0.8**/cdc (wd:/home/tidb/.tiup/data/SHWXc3S) failed: exit status 1
```

What method should be used to escape password with # sign?

When this password runs in tidb, there is no problem
![image](https://user-images.githubusercontent.com/21033020/100613210-202a2d00-334f-11eb-8ff8-cd06c43ffcb2.png)

Please help to check

**Comment by lance6716** [comment]
what's related error information in TiCDC? need that to locate BUG

**Comment by amyangfei** [comment]
The special character is not well processed now, but you can use the url encoded string as a workaround, as follows

`--sink-uri="mysql://username:123%23456@127.0.0.1:3306/"`

**Comment by lance6716** [comment]
BTW, seems our example sink uri is not very well formatted. For the AskTUG user's case, maybe `mysql://root:1234#56@tcp(172.16.188.189:3306)/` could work.

And I'm testing if a password containg `tcp(172.16.188.189:3306)` could work well

ref: https://github.com/go-sql-driver/mysql/issues/417

**Comment by amyangfei** [comment]
> BTW, seems our example sink uri is not very well formatted. For the AskTUG user's case, maybe `mysql://root:1234#56@tcp(172.16.188.189:3306)/` could work.
> 
> And I'm testing if a password containg `tcp(172.16.188.189:3306)` could work well
> 
> ref: [go-sql-driver/mysql#417](https://github.com/go-sql-driver/mysql/issues/417)

`sink-uri` supports both `URL scheme` format and `MySQL DSN` format in MySQL sink in TiCDC

**Comment by glkappe** [comment]
Thanks for your help
