### ISSUE TITLE
the grafana panel named "changefeed checkpoint" is misleading

### ISSUE THREAD

**Issue by leoppro** [pingcap/ticdc#1159]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

![image](https://user-images.githubusercontent.com/33834665/100837592-d7d45180-34ab-11eb-8aa6-22e510efaf2b.png)

the value of `ticdc_proccessor_checkpoint_ts` is the local checkpoint in a capture, but the panel title is `changefeed checkpoint`, it seems like a global checkpoint ts of a changefeed but IT IS NOT.

And the global checkpoint ts is not shown in grafana.

**Comment by amyangfei** [comment]
have been fixed in https://github.com/pingcap/ticdc/pull/1226
