### ISSUE TITLE
cdc cli changefeed admin operation blocked

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#1204]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

    Execute `cdc cli changefeed remove -c xxx` blocked.

2. What did you expect to see?

    command runs successfully

3. What did you see instead?

    ![20201214162858](https://user-images.githubusercontent.com/1527315/102057878-99368380-3e29-11eb-9326-91569c01c341.png)

    golang stack: 
[owner.log](https://github.com/pingcap/ticdc/files/5687451/owner.log)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        v4.0.7
        ```

    - TiCDC version (execute `cdc version`):

        ```
        v4.0.8
        ```

**Comment by leoppro** [comment]
Recurrent the bug:

https://github.com/pingcap/ticdc/pull/1205
Run integration tests in Github Action, we can recurrent this bug.

[see goroutine.log here](https://github.com/pingcap/ticdc/files/5687940/goroutine.log)

**Comment by leoppro** [comment]
fixed in tikv/pd#3283 and #1217
