### ISSUE TITLE
tidb sink to kafka cluster does it support?

### ISSUE THREAD

**Issue by masonone** [pingcap/ticdc#1243]
--sink-uri="kafka://127.0.0.1:9092/cdc-test?kafka-version=2.4.0&protocol=avro&partition-num=6&max-message-bytes=67108864&replication-factor=1"
--opts registry="http://127.0.0.1:8081"

sink-uri : Can multiple addresses be configured here？

**Comment by amyangfei** [comment]
If there exist multiple Kafka brokers, it can be configured with
`--sink-uri="kafka://kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092/cdc-test?kafka-version=2.4.0&protocol=avro&partition-num=6&max-message-bytes=67108864&replication-factor=1"`

**Comment by masonone** [comment]
> 如果存在多个Kafka代理，则可以使用
> `--sink-uri="kafka://kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092/cdc-test?kafka-version=2.4.0&..."`

Thank you, the test passed
