### ISSUE TITLE
Capture owner may become a hot spot

### ISSUE THREAD

**Issue by glkappe** [pingcap/ticdc#1245]
## Feature Request

**Is your feature request related to a problem? Please describe:**

当前 Capture 调度是以表为单位，当单表流量较大可能存在超过 Capture 调度能力问题

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by amyangfei** [comment]
duplicated with https://github.com/pingcap/ticdc/issues/1207

**Comment by glkappe** [comment]
thanks，i will close this issue
