### ISSUE TITLE
DDL lost after owner is killed (kill_owner_with_ddl fails)

### ISSUE THREAD

**Issue by liuzix** [pingcap/ticdc#1260]
DDL can be lost after adjusting order of owner operations. The owner now tries to flush changefeed status right after recalculating the ts's. Consider the following scenario:
- Owner recalculates the global checkpointTs to `A`, which is the finishTs of a DDL.
- Owner successfully upload the new the global checkpointTs, which gets persisted in Etcd.
- Owner gets killed before successfully executing DDL.
- New Owner thinks this DDL has already been executed.

This scenario is a conjecture, please comment if you have more thoughts on this.

**Comment by amyangfei** [comment]
Have been fixed by https://github.com/pingcap/ticdc/pull/1236.

the checkpoint won't be updated to DDL `FinishedTs` until the DDL has ben executed successfully
