### ISSUE TITLE
the compatibility issue between 4.0.x and 5.0.x

### ISSUE THREAD

**Issue by leoppro** [pingcap/ticdc#1306]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

There are some compatibility issue between 4.0.x and 5.0.x, when the cdc-cli's and cdc-server versions don't match.

If a mismatched cdc-cli creates a changefeed, the situation is as shown in the table below:

-  | server (0,4.0.8] | server [4.0.9,5.0) | server 5.0.0-rc
-- | -- | -- | --
cli (0,4.0.8] | Noraml | Normal | Runable with unexpected configuration[3]
cli [4.0.9,5.0) | Normal | Noraml | Runable with unexpected configuration[3]
cli 5.0.0-rc | server hang[1] | Runable with unexpected configuration[2] | Noraml

[1]: Causes the bug #1305
[2]: Create a changefeed with `old-value` enabled and `unified-sorter` as default value mistakenly
[3]: Create a changefeed with `old-value` disabled as default value mistakenly

## Root Cause

The `cdc-cli` in 5.0.x version using `old-value` enabled and `unified-sorter` as default value. But this configurations is not always effective in 4.0.x

## Solutions

- We can no longer modify the behavior of the released version, but can only inform users of the risks through documentation
- For the next release version (4.0.11 and 5.0.0-rc2 or 5.0.0)
    - For 4.0.11: the server should check the version of the changefeed-creator and make sure that the changefeed created by a 5.0.x cdc-cli will not be run in a 4.0.11 server
    - For 5.0.0-rc2: the cli should check the version of server, make sure that a 5.0.0 cli can't create a changefeed for a 4.0.x server

Some other tips

- Maybe we can add some compatibility tests, to avoid similar bugs happen in the future. Such as #1073 which changes `enable-old-value` from false to true, we can test with [TiDB 4.0.8](https://github.com/pingcap/ticdc/pull/1073#issuecomment-737618302), is it possible to add some TiCDC compatibility test matrix?

**Comment by zz-jason** [comment]
can we do a version check when a cli connects to a server, only allow the connection when the version between cli and server is the same? Thus we don't need to consider N*N combinations of compatibilities?

**Comment by zz-jason** [comment]
@IANTHEREAL what's your opinoin?

**Comment by IANTHEREAL** [comment]
agree with it

**Comment by amyangfei** [comment]
> It’s better not to have so many separate components for a tool. It is best to merge `cdc cli` into ticdc binary and provide a `cdc cli` subcommand.
> 
> In addition, I recommend to provide http/grpc api and add cli-related protocol version compatibility check for ticdc task management

There is no `cli` binary exactly, `cdc` only has **one** binary, and both `cdc server` and `cdc cli` are subcommands.

**Comment by leoppro** [comment]
update a faq about this issue: https://github.com/pingcap/docs-cn/pull/5411

**Comment by IANTHEREAL** [comment]
ok, TiCDC product allows users to use two versions binary, which needs to be well supported.
1. TiCDC interface needs to be standardized as soon as possible, supports http api and api version detection
2. tiup needs to be able to always use suitable cdc ctl binary
