### ISSUE TITLE
Replication stuck

### ISSUE THREAD

**Issue by liuzix** [pingcap/ticdc#1377]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
- Running several changefeeds with a mixture of kafka and mysql sinks.

2. What did you expect to see?
- That the replication proceeds smoothly.

3. What did you see instead?
- Some changefeeds stop making progress, with resolvedTs = checkpointTs.

4. Versions of the cluster

    - TiCDC version (execute `cdc version`):

        ```
        v4.0.9
        ```

**Comment by liuzix** [comment]
Update: problem seems to be caused by TiKV malfunction.

**Comment by amyangfei** [comment]
The cluster uses `v4.0.6` TiKV, and after more than 11 hours the cdc pullers are initialized finally.
During that peroid, the TiKV cdc endpoint CPU costs 100%, we suspect some deadloop happens in TiKV

**Comment by overvenus** [comment]
We have encountered and fixed several bugs similar to this issues, I'm going to close it since it has little information.
