### ISSUE TITLE
Log fold is unstable when doing create and drop table operation and thus affect br restore using cdc log

### ISSUE THREAD

**Issue by yuqi1129** [pingcap/ticdc#1415]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
1. create a table with primary key
2. create a ticdc change feed with s3 sink to track changes about the table(in fact, track the while tidb database)
3. insert some data to the table 
4. wait until ticdc export all the change to s3 and then drop / create table operation
5. do the 3 steps again

2. What did you expect to see?

All the changes should be the same fold as all the time table name has not changed

3. What did you see instead?

data change before the drop table operation and after table operation belong to different fold 

![image](https://user-images.githubusercontent.com/15794564/107168252-10396400-69f6-11eb-9728-4f1a65dce544.png)

when use cdc log to restore data, like `br restore cdclog` will failed to restore data...
4. Versions of the cluster
    

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        | Release Version: v4.0.8
Edition: Community
Git Commit Hash: 66ac9fc31f1733e5eb8d11891ec1b38f9c422817
Git Branch: heads/refs/tags/v4.0.8
UTC Build Time: 2020-10-30 08:21:16
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
        ```

    - TiCDC version (execute `cdc version`):

        ```
[work@c3-dba-benchmark-tidb01 ~]$ tiup cdc version
Starting component `cdc`: /home/work/.tiup/components/cdc/v4.0.10/cdc version
Release Version: v4.0.10
Git Commit Hash: bced60a8d65f31ab68a35f1f309ea2345076096c
Git Branch: heads/refs/tags/v4.0.10
UTC Build Time: 2021-01-14 12:38:40
Go Version: go version go1.13 linux/amd64
        ```

**Comment by IANTHEREAL** [comment]
@3pointer please help review this issue

**Comment by 3pointer** [comment]
Thanks for your reports. this is a bug that BR pick the [largest](https://github.com/pingcap/br/blob/master/pkg/restore/log_client.go#L315-L324) table id directory to restore. 

To fix this issue. we should choose the proper table id directory with given end-ts in `collectRowChangeFiles`.
1. traverse directories with the same table.
2. compute the smallest event ts in each directory.
3. find the proper directory. `directory smallest ts` < `end-ts` < `next directory smallest ts`

**Comment by overvenus** [comment]
s3 sink support will be removed soon, since there is a better alternative, the redo log. I'm going to close this issue, feel free to reopen if you have further questions, thanks!
