### ISSUE TITLE
ErrMySQLConnectionError: 1040: Too many connections

### ISSUE THREAD

**Issue by liuzix** [pingcap/ticdc#1486]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
- Ran TiCDC with a MySQL downstream. Added a pressure of 20000 qps to the upstream TiDB.

2. What did you expect to see?
- That the downstream remains available to other queries.

3. What did you see instead?
- Although replication proceeds, the downstream does not accept more connections, and reports `1040: Too many connections`

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        4.0.11
        ```

    - TiCDC version (execute `cdc version`):

        ```
        4.0.11
        ```

**Comment by amyangfei** [comment]
Could you please provide the following configuration
- TiCDC node count, sink `worker-count`, changefeed count
- the `max_connections` of downstream

**Comment by Tammyxia** [comment]
"worker-num": 16
================
mysql> show variables like 'max_connections';
+-----------------+-------+
| Variable_name   | Value |
+-----------------+-------+
| max_connections | 151   |
+-----------------+-------+
==================
$ tiup cdc cli changefeed query -c replication-task-1 --pd=http://172.16.5.105:2379
Starting component `cdc`: /root/.tiup/components/cdc/v4.0.11/cdc cli changefeed query -c replication-task-1 --pd=http://172.16.5.105:2379
{
  "info": {
    "sink-uri": "mysql://root:@172.16.5.107:3306/",
    "opts": {
      "_changefeed_id": "cli-verify"
    },
    "create-time": "2021-03-08T11:23:04.43804723+08:00",
    "start-ts": 423408116536705027,
    "target-ts": 0,
    "admin-job-type": 0,
    "sort-engine": "unified",
    "sort-dir": "/home/tidb/cdc/sort",
    "config": {
      "case-sensitive": true,
      "enable-old-value": false,
      "force-replicate": false,
      "check-gc-safe-point": true,
      "filter": {
        "rules": [
          "*.*"
        ],
        "ignore-txn-start-ts": null,
        "ddl-allow-list": null
      },
      "mounter": {
        "worker-num": 16
      },
      "sink": {
        "dispatchers": null,
        "protocol": "default"
      },
      "cyclic-replication": {
        "enable": false,
        "replica-id": 0,
        "filter-replica-ids": null,
        "id-buckets": 0,
        "sync-ddl": false
      },
      "scheduler": {
        "type": "table-number",
        "polling-time": -1
      }
    },
    "state": "normal",
    "history": [
      1615179803358
    ],
    "error": {
      "addr": "172.16.5.106:8300",
      "code": "CDC-owner-1001",
      "message": "rpc error: code = Unknown desc = rpc error: code = Unavailable desc = not leader"
    },
    "sync-point-enabled": false,
    "sync-point-interval": 600000000000,
    "creator-version": "v4.0.11"
  },
  "status": {
    "resolved-ts": 423411726941159425,
    "checkpoint-ts": 423411726679015425,
    "admin-job-type": 0
  },
  "count": 0,
  "task-status": [
    {
      "capture-id": "8e0bc5b4-63a0-4325-addc-dc2a63218f50",
      "status": {
        "tables": {
          "62": {
            "start-ts": 423409792604438724,
            "mark-table-id": 0
          },
          "63": {
            "start-ts": 423409792604438724,
            "mark-table-id": 0
          },
          "64": {
            "start-ts": 423409792604438724,
            "mark-table-id": 0
          },
          "65": {
            "start-ts": 423409792604438724,
            "mark-table-id": 0
          }
        },
        "operation": null,
        "admin-job-type": 0
      }
    }
  ]
}
==========================

**Comment by Tammyxia** [comment]
changeseed failed:
{
    "id": "replication-task-1",
    "summary": {
      "state": "failed",
      "tso": 423434349233307661,
      "checkpoint": "2021-03-09 15:10:54.192",
      "error": {
        "addr": "172.16.5.106:8302",
        "code": "CDC-owner-1001",
        "message": "fail to open MySQL connection: [CDC:ErrMySQLConnectionError]Error 1040: Too many connections"
      }
    }

**Comment by amyangfei** [comment]
1. TiCDC uses the default database pool provided by golang sql library, it should not leak MySQL connections. The cdc server count is **M**, the changefeed count is **N**, the `worker-num` parameter is **P**, then the **maximum** MySQL connections is **M * N * P**. Supposing M=3, N=4, P=16, the maximum MySQL connection count is 192
2. In local test, we didn't find database connection leak
3. The provided information is not completed to locate problem
4. Besides the default `max_connections` in MySQL is too small, it is common to use hundreds or thousands of database connections

IMHO this may not be a bug, but some misuse. I suggest to increase the `max_connections` parameter in MySQL, repeat the same test and observes the connections number with MySQL, either by `show global status like "Threads_connected";` or `show processlist`

**Comment by Tammyxia** [comment]
Reproduced it again.
Config: 3x capture,  2x changefeed, one cf has 16 worker-count, the other cf has 128 worker-count.
Download mysql  max_connection=1000

- $ tiup cdc:nightly cli changefeed list --pd=http://172.16.5.105:2379

Starting component `cdc`: /root/.tiup/components/cdc/v5.0.0-nightly/cdc cli changefeed list --pd=http://172.16.5.105:2379
[
  {
    "id": "replication-task-6",
    "summary": {
      "state": "stopped",
      "tso": 423632885722644481,
      "checkpoint": "2021-03-18 09:33:30.795",
      "error": {
        "addr": "172.16.5.106:8301",
        "code": "CDC:ErrProcessorUnknown",
        "message": "[CDC:ErrMySQLTxnError]Error 1040: Too many connections"
      }
    }
  },
  {
    "id": "replication-task-7",
    "summary": {
      "state": "stopped",
      "tso": 423632885722644481,
      "checkpoint": "2021-03-18 09:33:30.795",
      "error": {
        "addr": "172.16.5.106:8300",
        "code": "CDC:ErrProcessorUnknown",
        "message": "[CDC:ErrMySQLTxnError]Error 1040: Too many connections"
      }
    }
  }
]

**Comment by Tammyxia** [comment]
Changefeed sync time: 2021-03-18 09:11:56 to 2021-03-18 09:33:30

**Comment by amyangfei** [comment]
goroutines: [ticdc.routines.tar.gz](https://github.com/pingcap/ticdc/files/6161045/ticdc.routines.tar.gz)

The bug has been located, work in progress to fix it
