### ISSUE TITLE
Atomicity of transactions is broken in the downstream when using async commit

### ISSUE THREAD

**Issue by sticnarf** [pingcap/ticdc#1498]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

Run tipocket cdc-bank test with nemesis `shuffle-leader-scheduler,shuffle-region-scheduler,random-merge-scheduler,subcritical_skews,short_kill_tikv_1node` and tidb failpoints `github.com/pingcap/tidb/store/tikv/asyncCommitDoNothing=20%return;github.com/pingcap/tidb/store/tikv/twoPCShortLockTTL=return;github.com/pingcap/tidb/store/tikv/shortPessimisticLockTTL=return;github.com/pingcap/tidb/store/tikv/doNotKeepAlive=return;github.com/pingcap/tidb/store/tikv/invalidMaxCommitTS=10%return`.

2. What did you expect to see?

The test should pass.

3. What did you see instead?

The sum of account balance is not consistent, which means the atomicity of transactions is broken.

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
   
        TiDB 5.0 nightly.
       ```
       TiKV: 993ec6b818e20404cad2234c6314209a19f1074a
       TiDB: d1297376f1c9ab4835f3cfceec681ce4200aa428
       ```

    - TiCDC version (execute `cdc version`):

        ```
        Release Version: v5.0.0-master
        Git Commit Hash: 4f0e07ad92439b023403ed86b2fa8d517f4f0f36
        Git Branch: master
        UTC Build Time: 2021-03-11 09:39:33
        Go Version: go version go1.14.15 linux/amd64
        ```

**Comment by sticnarf** [comment]
Logs:

[logs.tar.xz.zip](https://github.com/pingcap/ticdc/files/6122736/logs.tar.xz.zip)

**Comment by sticnarf** [comment]
cc @leoppro for help

**Comment by amyangfei** [comment]
Please update the conclusion @leoppro

**Comment by amyangfei** [comment]
@leoppro has confirmed the atomicity of transaction is not broken. It is a false positive (broken) caused by test case, because TiCDC could execution transactions reentrant.
