### ISSUE TITLE
Fix flush size threshold of local file sink

### ISSUE THREAD

**Issue by yuqi1129** [pingcap/ticdc#1505]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

2. What did you expect to see?
![image](https://user-images.githubusercontent.com/15794564/111145220-fa095f80-85c2-11eb-86b4-19d0596e9428.png)

3. What did you see instead?
![image](https://user-images.githubusercontent.com/15794564/111145006-c3334980-85c2-11eb-87c8-542da0663953.png)
4. Versions of the cluster

    - TiCDC version (execute `cdc version`):

        ```
        master
        ```

**Comment by overvenus** [comment]
file sink support will be removed soon, since there is a better alternative, the redo log. I'm going to close this issue, feel free to reopen if you have further questions, thanks!
