### ISSUE TITLE
Sometimes query changefeed info failed

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#1509]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- 1. Stop changefeed: $ tiup cdc cli changefeed pause -c replication-task-6 --pd=http://172.16.5.105:2379
- 2. Check changefeed status: $ tiup cdc cli changefeed list --pd=http://172.16.5.107:2379
Starting component `cdc`: /root/.tiup/components/cdc/v4.0.11/cdc cli changefeed list --pd=http://172.16.5.107:2379
[2021/03/16 13:33:11.725 +08:00] [WARN] [client_changefeed.go:153] ["query changefeed info failed"] [error="Post http://172.16.5.106:8301/capture/owner/changefeed/query: dial tcp 172.16.5.106:8301: connect: connection refused"]
[
  {
    "id": "replication-task-6",
    "summary": null
  }
]

2. What did you expect to see?

3. What did you see instead?

- query changefeed info failed, query cli output has no changfeed status.
- Execute query cli again, there's right info.
$ tiup cdc cli changefeed list --pd=http://172.16.5.107:2379
Starting component `cdc`: /root/.tiup/components/cdc/v4.0.11/cdc cli changefeed list --pd=http://172.16.5.107:2379
[
  {
    "id": "replication-task-6",
    "summary": {
      "state": "stopped",
      "tso": 423591355341602818,
      "checkpoint": "2021-03-16 13:33:04.964",
      "error": null
    }
  }
]

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        4.0.11
        ```

    - TiCDC version (execute `cdc version`):

        ```
       4.0.11
        ```

**Comment by amyangfei** [comment]
IMO it is not a bug, the root cause is cdc server is down during querying
