### ISSUE TITLE
Fix file sink file format bug about version part

### ISSUE THREAD

**Issue by yuqi1129** [pingcap/ticdc#1514]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
   This issue is a little similar to https://github.com/pingcap/ticdc/issues/1422, which is about the version bug in s3 sink, however, this issue is targeted at the same bug in local file 
2. What did you expect to see?
None
3. What did you see instead?
None
4. Versions of the cluster

    
    - TiCDC version (execute `cdc version`):

        ```
        Master
        ```

**Comment by cyliu0** [comment]
Since file log is not GA, I'll decrease the severity for now.

**Comment by overvenus** [comment]
file sink support will be removed soon, since there is a better alternative, the redo log. I'm going to close this issue, feel free to reopen if you have further questions, thanks!
