### ISSUE TITLE
the error is not shown in `changefeed list` when executing DDL failed.

### ISSUE THREAD

**Issue by leoppro** [pingcap/ticdc#1536]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
create a changefeed with mysql sink.
a processor report an error when executing a DDL

2. What did you expect to see?
execute `cdc cli changefeed list`, and print the error

3. What did you see instead?
![image](https://user-images.githubusercontent.com/33834665/112275188-4be47080-8cba-11eb-9639-86869eed269b.png)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

v4.0.9

    - TiCDC version (execute `cdc version`):

v4.0.9

See https://internal.pingcap.net/jira/browse/ONCALL-2681 for detail

**Comment by overvenus** [comment]
We have mitigated this issue in the latest release, closed.
