### ISSUE TITLE
all CDC servers out of memory when incremental data is 9GB but CDC memory is 8GB

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#1543]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Deploy cluster and cdc in AWS VM.(2xTiDB, 3xPD, 3x TiKV, 3x CDC, 1x MySQL as downstream)
- Create 1x changefeed, then create new db in upstream.
- Pause changefeed. Wait sysbench insert 9GB data in upstream.
- Resume changefeed.

2. What did you expect to see?

3. What did you see instead?

- ![image](https://user-images.githubusercontent.com/78345569/112407340-e1cada80-8d50-11eb-9c06-77c2cabbbeef.png)

- 3x CDC servers are out of memory
[Wed Mar 24 08:24:24 2021] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/cdc-8300.service,task=cdc,pid=16467,uid=1001
[Wed Mar 24 08:24:24 2021] Out of memory: Killed process 16467 (cdc) total-vm:7511900kB, anon-rss:7361736kB, file-rss:0kB, shmem-rss:0kB, UID:1001 pgtables:14640kB oom_score_adj:0
[Wed Mar 24 08:24:24 2021] oom_reaper: reaped process 16467 (cdc), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
[Wed Mar 24 09:36:28 2021] systemd invoked oom-killer: gfp_mask=0x100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=0
[Wed Mar 24 09:36:28 2021] CPU: 0 PID: 1 Comm: systemd Not tainted 5.4.0-1038-aws #40-Ubuntu
[Wed Mar 24 09:36:28 2021] Hardware name: Amazon EC2 m5.large/, BIOS 1.0 10/16/2017

[Wed Mar 24 10:04:49 2021] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/cdc-8300.service,task=cdc,pid=2552,uid=1001
[Wed Mar 24 10:04:49 2021] Out of memory: Killed process 2552 (cdc) total-vm:7604080kB, anon-rss:7293932kB, file-rss:0kB, shmem-rss:0kB, UID:1001 pgtables:14792kB oom_score_adj:0

- Restart all components "tiup cluster restart tidb-test", after a few minutes, cdc server oom again.

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        Release Version: v4.0.0-beta.2-2435-g1cebae21a
Edition: Community
Git Commit Hash: 1cebae21a790e6ab161d36576dacadd041e39a65
Git Branch: master
UTC Build Time: 2021-03-23 13:05:42
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |

        ```

    - TiCDC version (execute `cdc version`):

        ```
      Release Version: v5.0.0-nightly-5-g3b8fb42
Git Commit Hash: 3b8fb42cd4661d484a509de251e917879197a1fe
Git Branch: release-5.0
UTC Build Time: 2021-03-19 10:28:44
Go Version: go version go1.13 linux/amd64

        ```

**Comment by amyangfei** [comment]
duplicated with https://github.com/pingcap/ticdc/issues/1150
