### ISSUE TITLE
"cdc cli changefeed update" will change Engine,SortDir unexpected

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#1544]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Create a changefeed Engine=unified, sink-uri=mysql
- cdc cli update sink-uri

2. What did you expect to see?

- Only sink-uri will be updated

3. What did you see instead?
Other option also will be updated automatically by default.
- ubuntu@ip-172-31-57-51:~$ tiup cdc cli changefeed update -c replication-task-1 --sink-uri="blackhole://" --pd=http://18.236.187.81:2379
Starting component `cdc`: /home/ubuntu/.tiup/components/cdc/v4.0.11/cdc cli changefeed update -c replication-task-1 --sink-uri=blackhole:// --pd=http://18.236.187.81:2379
Diff of changefeed config:
{Type:update Path:[SinkURI] From:mysql://tester:@34.223.88.229:3306/ To:blackhole://}
{Type:delete Path:[Opts _changefeed_id] From:replication-task-1 To:<nil>}
{Type:update Path:[Engine] From:unified To:memory}
{Type:update Path:[SortDir] From:. To:/tmp/cdc_sort}
{Type:update Path:[Config EnableOldValue] From:true To:false}
{Type:update Path:[CreatorVersion] From: To:v4.0.11}
Could you agree to apply changes above to changefeed [Y/N]
y
Update changefeed config successfully! Will take effect only if the changefeed has been paused before this command
ID: replication-task-1

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        (paste TiDB cluster version here)
        ```

    - TiCDC version (execute `cdc version`):

        ```
       cdc cli: 4.0.11
        ```

**Comment by amyangfei** [comment]
duplicated with #1545
