### ISSUE TITLE
When incremental data less than 3GB, cdc server need 30+ GB memory in local

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#1549]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Create changefeed with unified sorter enabled
- Execute "sysbench insert" in upstream TiDB 
- Pause changfeed, wait for half an hour to let upstream db has 2~3GB incremental data.
- Resume changfeed, check cdc server memory usage is 34GB

2. What did you expect to see?

3. What did you see instead?
 
![image](https://user-images.githubusercontent.com/78345569/112456058-5293e600-8d95-11eb-9d37-ce1edfbbd7bc.png)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        | Release Version: v5.0.0
Edition: Community
Git Commit Hash: b18eae98087148ad967d7fcbf6586ed7b9607c4b
Git Branch: heads/refs/tags/v5.0.0
UTC Build Time: 2021-03-24 15:31:59
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |

        ```

    - TiCDC version (execute `cdc version`):

        ```
        Release Version: v5.0.0-master
Git Commit Hash: d7fd39901c77a35914629e92f1ac4cb46e76e183
Git Branch: heads/refs/tags/v5.0.0
UTC Build Time: 2021-03-24 15:45:11
Go Version: go version go1.13 linux/amd64
        ```

**Comment by amyangfei** [comment]
Latest master doesn't have this problem, re-open the issue if it is reproduced.
