### ISSUE TITLE
cdc server memory usage always rise when resume changefeed to sync incremental data

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#1551]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Create a changefeed. Then create db in upstream TiDB,  sysbench insert to TiDB.
- Pause changefeed, wait for half an hour.
- Resume changfeed
- Repeate "pause cf-> insert data to TiDB for half an hours->resume cf" 5 times.

2. What did you expect to see?

3. What did you see instead?

- Each time resume changefeed, CDC server memory usage  rise about 4GB, never goes down.
It seems cdc server never release memory usage even changfeed stopped for a night.
In this situation, system memory will be centainly exhausted if pause/resume many times.

![image](https://user-images.githubusercontent.com/78345569/112577168-d1892d00-8e2e-11eb-9618-e16474d99aa7.png)

![image](https://user-images.githubusercontent.com/78345569/112577371-288f0200-8e2f-11eb-8318-7720968701de.png)

![image](https://user-images.githubusercontent.com/78345569/112577454-52e0bf80-8e2f-11eb-960f-74fae4bfae00.png)

- . Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        | Release Version: v5.0.0
Edition: Community
Git Commit Hash: b18eae98087148ad967d7fcbf6586ed7b9607c4b
Git Branch: heads/refs/tags/v5.0.0
UTC Build Time: 2021-03-24 15:31:59
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |

        ```

    - TiCDC version (execute `cdc version`):

        ```
        [release-version=v5.0.0-master] [git-hash=d7fd39901c77a35914629e92f1ac4cb46e76e183] [git-branch=heads/refs/tags/v5.0.0] [utc-build-time="2021-03-24 15:45:11"] [go-version="go version go1.13 linux/amd64"]
        ```

**Comment by amyangfei** [comment]
Since the released TiCDC is compiled with go1.13, go1.13 runtime releases memory in the `MADV_FREE` way, The kernel will only reclaim the unused data when it is needed. To revert to the behavior of `MADV_DONTNEED`, the environment variable GODEBUG=madvdontneed=1 should be set. IMHO this is not a bug.

**Comment by amyangfei** [comment]
Maybe we should consider to add `env GODEBUG=madvdontneed=1` in cdc startup script, just as TiDB does: https://github.com/pingcap/tiup/blob/6b3d44f0721cd9b83b0d4d4b4a6294467d7647be/embed/templates/scripts/run_tidb.sh.tpl#L21-L23
@Tammyxia

**Comment by amyangfei** [comment]
The recent test on master doesn't have memory leak, re-open the issue if we reproduce it.
