### ISSUE TITLE
changfeed checkpoint don't move on while the status is normal

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#1561]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Pause changefeed 
- Restart tidb cluster, scale-in cdc server
- Resume changefeed

2. What did you expect to see?

3. What did you see instead?

- changefeed checkpoint don't move one even for one night
- 
![image](https://user-images.githubusercontent.com/78345569/112707874-8122d580-8ee9-11eb-8120-e0fc40111dda.png)

![image](https://user-images.githubusercontent.com/78345569/112708087-cf84a400-8eea-11eb-90f6-c1335d2e6da5.png)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
      | Release Version: v5.0.0
Edition: Community
Git Commit Hash: b18eae98087148ad967d7fcbf6586ed7b9607c4b
Git Branch: heads/refs/tags/v5.0.0
UTC Build Time: 2021-03-24 15:31:59
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |

        ```

    - TiCDC version (execute `cdc version`):

        ```
Release Version: v5.0.0-master
Git Commit Hash: a34a830971d7d5e897ed212dc3188637c420e25f
Git Branch: heads/refs/tags/v5.0.0-nightly
UTC Build Time: 2021-03-25 11:09:00
Go Version: go version go1.13 linux/amd64

        ```

**Comment by Tammyxia** [comment]
![image](https://user-images.githubusercontent.com/78345569/112709934-5e4bed80-8ef8-11eb-9c91-57dda77b6611.png)
![image](https://user-images.githubusercontent.com/78345569/112710086-8ab43980-8ef9-11eb-9448-b1537d6eda59.png)

**Comment by amyangfei** [comment]
The tests focus on replicating historical incremental data with large regions (>100K), but the OOM of TiCDC happens a lot which affects the tests badly. The block of replication is a result of OOM.
The tests won't continue until the OOM issue of TiCDC is finally solved.

**Comment by amyangfei** [comment]
The workload is not defined in issue, and since OOM problem is solved, this issue has no more valuable information, just close it.
