### ISSUE TITLE
CDC server still OOM in 5.0 fixed version

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#1590]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Upstream incremental data < 10GB, CDC server's memory is 64GB.
- Resume changfeed.

2. What did you expect to see?

3. What did you see instead?

- CDC server OOM 
- 
![image](https://user-images.githubusercontent.com/78345569/113113302-bb1f0f00-923c-11eb-9970-e9b6f54374a4.png)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        v5.0.0-nightly
        ```

    - TiCDC version (execute `cdc version`):

        ```
       [release-version=v5.1.0-master-dirty] [git-hash=7863b3bcff630ab90fa2cb2fa6798832ca06be83] [git-branch=mem_patch1] [utc-build-time="2021-03-29 13:35:58"] 
        ```

**Comment by amyangfei** [comment]
duplicated with https://github.com/pingcap/ticdc/issues/1386

**Comment by Tammyxia** [comment]
TiDB owns table count is about 1.5k

**Comment by overvenus** [comment]
We have solved several OOM issue after since, I believe this issue has been fixed in latest release, closed, Feel free to reopen if TiCDC still OOMs
