### ISSUE TITLE
owner changefeed info is not up to date which causes gc safepoint advances unexpectedly

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#1605]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

   1. Set up a cdc cluster with 3 nodes and create two changefeeds, replicate to MySQL-1 and MySQL-2 respectively. The changefeeds work normally.
   2. Shutdown MySQL-1, the changefeed-1 will soon stop.
   3. Resume changefeed-1, the changefeed will retry but fail.
   4. Change cdc owner
   5. The new owner will try to start changefeed-1, but will fail at last.
   6. The calculation of gc safepoint will not take changefeed-1 into consideration, after gc safepoint exceeds, the changefeed will become `failed` state.

2. What did you expect to see?

   The gc safepoint should not advance

3. What did you see instead?
   
    The gc safepoint advances

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        5.0.0

    - TiCDC version (execute `cdc version`):

        In 4.0.x, 5.0.0 and master

**Comment by asddongmen** [comment]
The bug does not exist in the new owner.  
Perhaps the severity of the bug can be lowered.

**Comment by asddongmen** [comment]
@amyangfei Do you think we can close this issue now? The new owner are released in all released cdc branch.
