### ISSUE TITLE
cdc report panic when check changfeed config failed

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#1622]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
Execute "$ tiup cdc:nightly cli changefeed update --config changfeed.toml --pd=http://172.31.10.94:2379 -c "replication-task-1"", while config file changfeed.toml has wrong format.

2. What did you expect to see?
CDC report error not panic

3. What did you see instead?
![image](https://user-images.githubusercontent.com/78345569/114121913-d87d6880-9921-11eb-9395-dbd256b54982.png)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        v5.0.0-nightly, Git Commit Hash: 09a4c57d00175ae3ff9c900d5fb67f6757c58181
        ```

    - TiCDC version (execute `cdc version`):

        ```
       release-version=v5.0.0-master] [git-hash=b33b7fa15b4986db069cfc031bcd7fb827207b0b]
        ```

**Comment by amyangfei** [comment]
Good catch, `cdc cli changefeed create` has the same problem
