### ISSUE TITLE
Question ask: How to know the changefeed task is completed?

### ISSUE THREAD

**Issue by mahjonp** [pingcap/ticdc#166]
I'm going to bench the performance of CDC. I populate some data into the upstream TiDB cluster and after it's finished, I run cdc cli, and get some info like:

```
create changefeed detail &{SinkURI:root@tcp(127.0.0.1:3306)/test Opts:map[] CreateTime:2019-12-09 21:11:09.219849281 -0500 EST m=+0.017868850 StartTs:413114580074496000 TargetTs:0 Info:<nil>}
```

The sync task is running on cli server, so How do I know data is synced?

**Comment by amyangfei** [comment]
Add a `ctrl` command in #169 
We can start a changefeed with a `target-ts`, and check the `checkpoint-ts` of replication status of this changefeed by
```
➜  ./bin/cdc ctrl --cmd=query-cf-status --changefeed-id=a2339fed-d360-4726-bd42-f2f0c08daa44
{"sink-uri":"root@tcp(127.0.0.1:3306)/test","resolved-ts":413128531400720385,"checkpoint-ts":413128528739696641}
```
