### ISSUE TITLE
The abnormal changefeed impact other normal changefeed to sync task

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#1708]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- There are two changfeed, "replication-task-1" created with correct parameters, "replication-task-2" created with incorrect parameters.
- First there's no any data write, two changefeed's checkpint is the latest time.
- Then sysbench insert 20 tables.
- Check the changfeed status.

2. What did you expect to see?
The normal changfeed "replication-task-1" works fine.
The abnormal changfeed "replication-task-2" don't sync any data.
3. What did you see instead?
"replication-task-1"  changefeed also get stuck.
![image](https://user-images.githubusercontent.com/78345569/116224951-d28de100-a783-11eb-9c15-1381092e5654.png)
[2021/04/27 18:10:19.004 +08:00] [WARN] [owner.go:216] ["task position not found, fallback to use changefeed checkpointts"] [capture-id=7e9998a8-16cf-405d-8a32-c86dc703111d] [changefeed=replication-task-2]
[2021/04/27 18:10:19.009 +08:00] [WARN] [owner.go:216] ["task position not found, fallback to use changefeed checkpointts"] [capture-id=7e9998a8-16cf-405d-8a32-c86dc703111d] [changefeed=replication-task-1]

Check downstream db, part of DDL executed, sysbench create 20 tables in upstream, but downstream only has 2 tables.
4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
       5.0.0-nightly
        ```

    - TiCDC version (execute `cdc version`):

        ```
        5.0.0-nightly
        ```

**Comment by Tammyxia** [comment]
After 30+ minutes checkpoint lag, remove  abnormal changfeed "replication-task-2" , check replication-task-1 can sync task to the latest time.

**Comment by amyangfei** [comment]
Please upload cdc server log

**Comment by Tammyxia** [comment]
cdc log size is 300MB that cannot be uploaded to github.

**Comment by Tammyxia** [comment]
[cdc.tar.gz](https://github.com/pingcap/ticdc/files/6404169/cdc.tar.gz)

**Comment by amyangfei** [comment]
Since new owner has been enabled in https://github.com/tikv/tikv/pull/11352, since v5.0.5. The related code in this issue has been removed. Close this issue now.
