### ISSUE TITLE
changefeed-id need to be limit  max length

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#1709]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Create changefeed with very long character in changefeed-id:
]# tiup cdc cli changefeed create --pd=http://172.16.6.53:2379 --sink-uri='mysql://root:Pingcap!%40%231@172.16.4.142:3306/@#$/?time-zone=SYSTEM'   --changefeed-id=Rreplica11111111111111111111111fdsfaaaaaddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddqqqqqqqqqqqqqqqqqqqqqqqqqttttttttttttttttttttt9999999999999999999999999999999999999999999999kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk88888888888888888888888888888888888888888888888888

2. What did you expect to see?
The command failed to execute.
3. What did you see instead?
The command succesful:

![image](https://user-images.githubusercontent.com/78345569/116231239-349e1480-a78b-11eb-9061-bb5eec451edf.png)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        5.0.0-nightly
        ```

    - TiCDC version (execute `cdc version`):

        ```
        5.0.0-nightly
        ```

**Comment by ben1009** [comment]
![image](https://user-images.githubusercontent.com/1741864/122189148-42d2fc00-cec3-11eb-8849-cb1160d6eafd.png)
fixed by add a limitation check

**Comment by amyangfei** [comment]
closed by #2054
