### ISSUE TITLE
Changefeed: Deadlock found when replicating the same table multiple times to the same downstream

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#1717]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Create 3x changefeed with the same upstream db and downstream db
![image](https://user-images.githubusercontent.com/78345569/116342773-c0f51980-a815-11eb-9616-d3e253a3abee.png)

- 

2. What did you expect to see?

- CDC do't allow user to create the totally same changefeed, or other optimize to avoid deadlock .

3. What did you see instead?

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
       5.0.0-nightly
        ```

    - TiCDC version (execute `cdc version`):

        ```
       5.0.0-nightly
        ```

**Comment by overvenus** [comment]
Deadlocks are inevitable in this case, we should never setup multiple changefeed that replicating the same table to the same downstream.
