### ISSUE TITLE
Fail-fast for unrecoverable DML errors

### ISSUE THREAD

**Issue by liuzix** [pingcap/ticdc#1724]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Users can be frustrated if an unrecoverable error such as `tableNotExists` is not reported in a timely fashion.

**Describe the feature you'd like:**
Instead of retrying, the sink should fail fast when a DML error is likely to be unrecoverable without manual intervention.

**Describe alternatives you've considered:**
Report currently on-going retries.

**Teachability, Documentation, Adoption, Migration Strategy:**
We should take care to ensure that failed changefeeds are periodically retried, in case the user completed the manual intervention and expects the changefeed to continue on its own.

**Comment by amyangfei** [comment]
duplicated with https://github.com/pingcap/ticdc/issues/525

**Comment by ben1009** [comment]
close this one, all prs got merged
