### ISSUE TITLE
v5.0.1 - ticdc - fail to open MySQL connection: [CDC:ErrMySQLConnectionError]Error 1238: Variable 'explicit_defaults_for_timestamp' is a read only variable

### ISSUE THREAD

**Issue by glkappe** [pingcap/ticdc#1760]
Because of the table.t created first, this table will not be synchronized, in order to distinguish it from the above issues

**_PS：The ip, port and user in issues have been desensitized_**

https://github.com/pingcap/ticdc/pull/1638

**cmd：**
tiup ctl:v5.0.1 cdc changefeed create --pd=http://172.16.4.107:12379 --sink-uri="mysql://**root**:123456@**172.16.4.107**:3306" --changefeed-id=test_daxiaoxie --config=./ticdc.toml

[tidb@node4107 conf]$ cat ticdc.toml 
case-sensitive = false
[filter]
rules = ['ticdc.*']

tables in tidb.ticdc ：
mysql> show tables;
+-----------------+
| Tables_in_ticdc |
+-----------------+
| t               |
+-----------------+
1 row in set (0.00 sec)

mysql> show create table t;
| Table | Create Table                                                                                                                                                    |
| t     | CREATE TABLE `t` (
  `id` int(11) NOT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
1 row in set (0.01 sec)

**error：**
fail to open MySQL connection: [CDC:ErrMySQLConnectionError]Error 1238: Variable 'explicit_defaults_for_timestamp' is a read only variable

**tidb sql_mode：**
mysql> show variables like '%sql_mode%';
+---------------+--------------------------------------------+
| Variable_name | Value                                      |
+---------------+--------------------------------------------+
| sql_mode      | **STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION** |
+---------------+--------------------------------------------+
1 row in set (0.53 sec)

mysql> select tidb_version()'
    '> ';
**| Release Version: v5.0.1**
Edition: Community
Git Commit Hash: 1145e347d3469d8e89f88dce86f6926ca44b3cd8
Git Branch: heads/refs/tags/v5.0.1
UTC Build Time: 2021-04-23 05:51:17
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
1 row in set (0.00 sec)

**mysql sql_mode：**

mysql> show variables like 'sql_mode';
+---------------+--------------------------------------------+
| Variable_name | Value                                      |
+---------------+--------------------------------------------+
| sql_mode      | **STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION** |
+---------------+--------------------------------------------+
1 row in set (0.00 sec)

mysql> \s;
--------------
mysql  Ver 14.14 Distrib 5.6.48-88.0, for Linux (x86_64) using  6.2

Connection id:		20
Current database:	
Current user:		root@node4107
SSL:			Not in use
Current pager:		stdout
Using outfile:		''
Using delimiter:	;
Server version:		5.6.48-88.0-log Percona Server (GPL), Release 88.0, Revision 66735bc
Protocol version:	10
Connection:		172.16.4.107 via TCP/IP
Server characterset:	latin1
Db     characterset:	latin1
Client characterset:	utf8
Conn.  characterset:	utf8
TCP port:		3306
Uptime:			9 days 3 hours 56 min 7 sec

Threads: 1  Questions: 112  Slow queries: 0  Opens: 88  Flush tables: 1  Open tables: 81  Queries per second avg: 0.000

**Comment by amyangfei** [comment]
This is a known issue in v4.0.12/v5.0.1, when replicating data to MySQL. The MySQL account provided in sink-uri must have `super` privilege.
We will remove this privilege requirement in v4.0.13 and v5.0.2

**Comment by glkappe** [comment]
**Sorry, add the permissions of root@% in mysql**



**Welcome** to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 22
Server version: 5.6.48-88.0-log Percona Server (GPL), Release 88.0, Revision 66735bc

Copyright (c) 2009-2020 Percona LLC and/or its affiliates
Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show grants;
+--------------------------------------------------------------------------------------------------------------------------------+
| Grants for root@%                                                                                                              |
+--------------------------------------------------------------------------------------------------------------------------------+
| GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY PASSWORD '*6BB4837EB74329105EE4568DDA7DC67ED2CA2AD9' WITH GRANT OPTION |
+--------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)

mysql> select host , user from mysql.user;
+-----------------------+-----------+
| host                  | user      |
+-----------------------+-----------+
| %                     | dump_user |
| %                     | mysqldm   |
| %                     | root      |
| %                     | t         |
| 127.0.0.1             | root      |
| ::1                   | root      |
| localhost             |           |
| localhost             | root      |
| localhost.localdomain |           |
| localhost.localdomain | root      |
+-----------------------+-----------+
10 rows in set (0.01 sec)

mysql> select user();
+---------------+
| user()        |
+---------------+
| root@node4107 |
+---------------+
1 row in set (0.01 sec)

**Comment by glkappe** [comment]
Percona-mysql-5.6 has explicit_defaults_for_timestamp parameter, and sink user permission is all privileges How to explain this error.
@amyangfei

**Comment by amyangfei** [comment]
> Percona-mysql-5.6 has explicit_defaults_for_timestamp parameter, and sink user permission is all privileges How to explain this error.

Do you mean event use user with `all` privilege still can't set `explicit_defaults_for_timestamp`?

**Comment by glkappe** [comment]
@amyangfei  yes，picture，point is percona-56

![image](https://user-images.githubusercontent.com/21033020/118413345-68f15a80-b6d1-11eb-87c3-92ce03c4aebd.png)

![image](https://user-images.githubusercontent.com/21033020/118413327-59721180-b6d1-11eb-89dd-4146eec5d412.png)

![image](https://user-images.githubusercontent.com/21033020/118413368-8faf9100-b6d1-11eb-9e40-c2fea9e2e74b.png)

**Comment by glkappe** [comment]
@amyangfei any update

**Comment by amyangfei** [comment]
> Percona-mysql-5.6 has explicit_defaults_for_timestamp parameter, and sink user permission is all privileges How to explain this error.

Then TiCDC 5.0.1/v4.0.12 doesn't support `Percona-mysql-5.6`, no workaound

Please wait v5.0.2/v4.0.13 or use the older version

**Comment by glkappe** [comment]
ok
