### ISSUE TITLE
Monitor shows cdc owner switched but cdc log has not

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#1815]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- From CDC monitor, it seems owner switched frequently
    
![image](https://user-images.githubusercontent.com/78345569/119073889-9d8e4a80-ba20-11eb-88ae-49391d2588a2.png)

- But check cdc.log, there's no owner exited:
   
![image](https://user-images.githubusercontent.com/78345569/119073988-cc0c2580-ba20-11eb-9f69-f95c08969c99.png)

2. What did you expect to see?

- Monitor match with log  for owner switched message.

3. What did you see instead?

- They are different, monitor shows owner switched, but cdc log shows owner has not switched.

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
       v4.0.0-beta.2-2923-g44830b917-dirty,  Git Commit Hash: 44830b917465c5d46cd22f617a3e260f09f0b857
        ```

    - TiCDC version (execute `cdc version`):

        ```
         [release-version=v5.0.0-master] [git-hash=f04762b8076858217ab77ed175721b3fb65d3a46] [git-branch=master] [utc-build-time="2021-05-18 15:46:16"] [go-version="go version go1.13 linux/amd64"]
        ```

**Comment by overvenus** [comment]
As long as the value not reach 0, we should not consider it owner switch, as metrics has certain inaccuracy.
