### ISSUE TITLE
Add more document about gc-ttl and service gc safepoint

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#1825]
## Feature Request

**Is your feature request related to a problem? Please describe:**

- `gc-ttl` is not editable before tiup v1.4.3 (v1.4.3 included)
- We have made a large change of the GC safepoint update strategy in #1731 

**Describe the feature you'd like:**

- [x] We should add document to describe what have been changed since #1731. 
- [x] We should add document to tell user how to change `gc-ttl` with TiUP.
- [x] We should add more documents to describe the usage of `gc-ttl` from the point of a user, with a more intuitive way.

**Comment by asddongmen** [comment]
I will do this soon.
