### ISSUE TITLE
kv oom when tidb has data writing and cdc incremental data sync task 

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#1844]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Resume changefeed which incremental data size is 200GB.
- Meanwhile,  lightning load data to upstream TiDB
- Env: 56 table count, 1x changefeed, 1x CDC server 64GB memory, 1x TiKV 64GB memory, 

2. What did you expect to see?
No any OOM.
3. What did you see instead?
kv oom
![image](https://user-images.githubusercontent.com/78345569/119620467-98be0200-be37-11eb-913f-a0d6a5564a46.png)
![image](https://user-images.githubusercontent.com/78345569/119620489-9fe51000-be37-11eb-96c5-ea1b793f2d64.png)
![image](https://user-images.githubusercontent.com/78345569/119620500-a3789700-be37-11eb-8929-16c6df6ed18e.png)

If stop lightning to load data, kv will not has oom. Or if there's no cdc sync task, only lightning load data to TiDB, also there's no kv oom.
 4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        5.0.0-nightly 05-24-2021
        ```

    - TiCDC version (execute `cdc version`):

        ```
       5.0.0-nightly 05-24-2021
        ```

**Comment by overvenus** [comment]
This is related to https://github.com/tikv/tikv/issues/10114 .
