### ISSUE TITLE
Changefeed checkpoint get stuck after resume，network latency 100ms

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#1864]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Pause changefeed, tc add tidb cluster network latency 100ms.
- sysbench insert to upstream TiDB for 5 minutes, add network latency 100ms for 2 minutes.
- Resume changefeed, tc del tidb cluster network latency, now ping tidb cluster only < 1ms network latency.
- Find CF checkpoint don't move on.

2. What did you expect to see?

- CF checkpoint can move on.

3. What did you see instead?

- 
![image](https://user-images.githubusercontent.com/78345569/119923356-20288400-bfa4-11eb-953c-f7ffef96e700.png)

![image](https://user-images.githubusercontent.com/78345569/119923062-9e385b00-bfa3-11eb-8644-0af3fdfe173d.png)
![image](https://user-images.githubusercontent.com/78345569/119935034-663c1280-bfb9-11eb-8d83-270c64a450c4.png)

Delete the old cf replication-task-c, check the new cf checkpoint still cannot move on.
4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
       5.0.0-nightly 05-24
        ```

    - TiCDC version (execute `cdc version`):

        ```
       5.0.0-nightly 05-24
        ```

**Comment by amyangfei** [comment]
The log shows latency is larger than 500ms?

**Comment by amyangfei** [comment]
```
$ grep "cdc region is ready" tikv.log|awk '{print $2}'|awk -F. '{print $1}'|sort|uniq -c|sort -k1 -rn|head
     39 13:49:16
     37 14:03:20
     37 14:01:22
     36 14:05:22
     36 14:03:40
     36 14:01:46
     36 14:01:17
     36 13:59:10
     36 13:49:17
     35 14:05:05
```

I found the speed that TiKV initializes region is limited, less than 40 per seconds, there exists 68375 regions in the TiKV

**Comment by amyangfei** [comment]
The changefeed can be initialized, but slowly because of the scan limit in TiKV, which is as expected. So this is not a bug, please confirm and change the label @Tammyxia

**Comment by Tammyxia** [comment]
This can be closed, but please pay pattention the scan limit setting in TiKV, make balance between kv oom and cdc sync speed.
