### ISSUE TITLE
70k region, 1x kv node, cdc sync task don't move on 2+ days cauz waiting for kv initiazation since kv client always reconnected 

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#1889]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Real-time sync task by CDC
- Sysbench insert to upstream TiDB (qps 5000) for 2 days， kv region is 70K.
- Stop sysbench writing on TiDB. Waiting for 3 hours.

2. What did you expect to see?
CDC cf sync task has not too much lag.

3. What did you see instead?

test1.* resolved ts has lagged behind other tables for 2+ days.
![image](https://user-images.githubusercontent.com/78345569/120150999-56713800-c21e-11eb-91cd-8785ca6d9dee.png)
log: 
[2021/05/31 10:39:09.504 +08:00] [WARN] [region_worker.go:304] ["kv client reconnect triggered"] [duration=15m57.444008331s] [region=148675]

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        Release Version: v5.1.0-alpha-13-gd5e0ed0aa-dirty
Edition: Community
Git Commit Hash: d5e0ed0aaed72d2f2dfe24e9deec31cb6cb5fdf0
Git Branch: master
UTC Build Time: 2021-05-24 14:39:20
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |

        ```

    - TiCDC version (execute `cdc version`):

        ```
       Release Version: v5.0.0-master
Git Commit Hash: a68022698c6a7c5d652199603c23d0df56e19cc4
Git Branch: master
UTC Build Time: 2021-05-24 10:22:22
Go Version: go version go1.13 linux/amd64
Failpoint Build: false
        ```

**Comment by amyangfei** [comment]
closed by https://github.com/pingcap/ticdc/pull/1979
