### ISSUE TITLE
changefeed info has specific sort-dir directory but acctually it don't take effect

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#1960]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Create changefeed with --sort-dir=/home/tidb, from cli output, it seems sort-dir works:
![UGsFI8fc9q](https://user-images.githubusercontent.com/78345569/120950282-0ee83000-c779-11eb-8e94-1c6baab77c4c.png)

- Run sysbench insert in upstream, find sort-dir is still /tmp by default:
![kc6VScxqPy](https://user-images.githubusercontent.com/78345569/120950406-4656dc80-c779-11eb-818f-65ec06b394a3.png)

2. What did you expect to see?

- I know --sort-dir don't take effect in create changefeed command, because CDC server also has sort-dir(/tmp) and it override changefeed cli sort-dir. But changefeed cli should tell user with the correct sort-dir

3. What did you see instead?
changefeed info has the sort-dir(/home/tidb)  don't take effect.
4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        5.0.2
        ```

    - TiCDC version (execute `cdc version`):

        ```
       5.0.2
        ```

**Comment by amyangfei** [comment]
solved in https://github.com/pingcap/ticdc/pull/1879
