### ISSUE TITLE
Document about cdc gc-ttl need to be add in https://github.com/pingcap/docs-cn/blob/release-5.0/config-templates/complex-cdc.yaml

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#1961]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Now https://github.com/pingcap/docs-cn/blob/release-5.0/config-templates/complex-cdc.yaml has not cd gc-ttl config. 
- There's internal user donot' know how to setup gc-ttl in deploy yaml cdc file.

2. What did you expect to see?

3. What did you see instead?

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
       5.0.2
        ```

    - TiCDC version (execute `cdc version`):

        ```
        5.0.2
        ```

**Comment by asddongmen** [comment]
I will do this in the next week.

**Comment by asddongmen** [comment]
done
