### ISSUE TITLE
cdc oom when sysbench prepare to create 1000 tables

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#1962]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Create changefeed with filter one database.
- Run sysbench to create tables "# sysbench oltp_common prepare --db-driver=mysql --mysql-host=172.16.6.13 --mysql-port=3306 --mysql-user=root --mysql-password= --mysql-db=tammy --threads=512 --tables=1000 --table-size=0"

2. What did you expect to see?

- sync task completed without any error

3. What did you see instead?

- sync task complete, but cdc oom:
![xOdmxikGXI](https://user-images.githubusercontent.com/78345569/120952991-ba47b380-c77e-11eb-8e1a-d316ef203a2b.png)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        5.0.2
        ```

    - TiCDC version (execute `cdc version`):

        ```
       5.0.2
        ```

**Comment by Tammyxia** [comment]
cdc server: cpu 8c, memory 16GB.

**Comment by amyangfei** [comment]
We have optimized the memory usage under 16G host ref: https://github.com/pingcap/ticdc/pull/1915, https://github.com/pingcap/ticdc/pull/1999
