### ISSUE TITLE
Doc about gc-ttl and sort-dir, need more explanation to user, since gc-ttl and sort-dir are very import parameters

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#1963]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Now the explanation about gc-ttl and sort-dir are too little, but they are very important for user to sync data.
- https://docs.pingcap.com/zh/tidb/stable/deploy-ticdc#ticdc-cdc-server-%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E
![image](https://user-images.githubusercontent.com/78345569/120953896-9a18f400-c780-11eb-8cc3-d37dd0f57ab5.png)
![image](https://user-images.githubusercontent.com/78345569/120953913-a2712f00-c780-11eb-93a5-c50bc8b05c8c.png)

- Here's there's no tiup compatibility info. with cdc "config":
https://docs.pingcap.com/zh/tidb/stable/tiup-cluster-topology-reference#cdc_servers
![image](https://user-images.githubusercontent.com/78345569/120954130-0dbb0100-c781-11eb-9845-060af150f70e.png)

2. What did you expect to see?

3. What did you see instead?

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
       5.0.2
        ```

    - TiCDC version (execute `cdc version`):

        ```
        5.0.2
        ```

**Comment by overvenus** [comment]
We have enhanced these paramaters in https://github.com/pingcap/docs-cn/pull/7041. Feel free to reopen this issue if you have further questions, thanks!
