### ISSUE TITLE
Confusing error message when not passing certificate paths correctly with HTTPS PD URI

### ISSUE THREAD

**Issue by liuzix** [pingcap/ticdc#1973]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
`/cdc cli changefeed create --pd=https://db-pd:2379 --sink-uri="mysql://root:*****@*****:4000/"`

2. What did you expect to see?
- CDC reporting that certificates are expected

3. What did you see instead?
- `PD endpoint scheme should be http`

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        v4.0.11
        ```

    - TiCDC version (execute `cdc version`):

        ```
        v4.0.11
        ```

**Comment by hi-rustin** [comment]
I am working on this.
