### ISSUE TITLE
cdc oom when sync historical data 40-50GB in cdc server 8C 16G

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#1974]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- CDC server: CPU 8 cores, memory 16GB. 2 x CDC server.
- Create changefeed with filter 10 tables.
- Run "# sysbench oltp_insert run --db-driver=mysql --mysql-host=xxx --mysql-port=3306 --mysql-user=root --mysql-password= --mysql-db=tammy --threads=512 --tables=10 --time=360000 --report-interval=10",  after 5 minutes, check sync task works normally, no checkpoint lag.
- Pause this changefeed. Waiting for about half an hours, check sysbench data increased about 40GB in upstream database.
- Resume this changefeed. Then stopping sysbench insert.

2. What did you expect to see?

- No error/oom, sync task completed.

3. What did you see instead?

- CDC OOM.
- CDC metric:
![image](https://user-images.githubusercontent.com/78345569/120972788-b4fb6080-c7a0-11eb-9be8-f2172c675483.png)
![image](https://user-images.githubusercontent.com/78345569/120972842-c3497c80-c7a0-11eb-8c46-e770d39ee0ca.png)
![image](https://user-images.githubusercontent.com/78345569/120972927-db210080-c7a0-11eb-8b7f-a0d04f3713da.png)

- TiKV metric:
![image](https://user-images.githubusercontent.com/78345569/120973435-83cf6000-c7a1-11eb-9f2c-598100f1166e.png)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        5.0.2
        ```

    - TiCDC version (execute `cdc version`):

        ```
       5.0.2
        ```

**Comment by Tammyxia** [comment]
CDC server system log:
![image](https://user-images.githubusercontent.com/78345569/120973624-c133ed80-c7a1-11eb-9494-337fa225b1cd.png)

**Comment by Tammyxia** [comment]
This CDC OOM is always continue and sync task cannot complete after resume half an hours.

**Comment by amyangfei** [comment]
It is a known issue that v5.0.2 could OOM with 8C16G, we will fix this issue in v5.0.3 and v5.1.0.
ref: https://github.com/pingcap/ticdc/pull/1915
https://github.com/pingcap/ticdc/pull/1949
