### ISSUE TITLE
new_owner:  CDC canot  rebalance again after one node down and restart.

### ISSUE THREAD

**Issue by asddongmen** [pingcap/ticdc#1991]
Please answer these questions before submitting your issue. Thanks!
@leoppro 
1. What did you do? If possible, provide a recipe for reproducing the error.

3 TiKV, 3 TiDB, 3 PD, and 3 TiCDC are deployed on three different servers.

```shell
# Test flow:
# -> Set const NewReplicaImpl = true
# -> build master TiCDC
# -> patch the cluster
# -> drop database tpcc (if exist)
# -> Reset the status of the TiCDC cluster
# -> create 30 changefeed at begin (--sink-uri="blackhole://")
# -> write data into TiDB: tiup bench tpcc -H 172.16.6.125 -P 4000 -D tpcc100 --warehouses 100  prepare
# -> Gradually increase the number of changefeed, increasing by 10 each time
```

After running for about 10 minutes in the case of 30 changefeeds, the CDC owner node down, and then automatically restarts soon. 

Since then, the restarted node has not obtained enough tasks again, and the load among the nodes of the CDC cluster is not balanced.
  
<img width="827" alt="微信图片_20210609133126" src="https://user-images.githubusercontent.com/20351731/121298811-10eff180-c927-11eb-87d0-4a791ba0640f.png">

2.What did you expect to see?

CDC can rebalance again, each node should be assigned a similar number of tasks.

3. What did you see instead?

CDC canot  rebalance again，one node has a small amount of tasks, while the other two nodes have a lot of tasks.

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
         Release Version: v5.1.0-alpha-167-ga8ad9b7d3
         Edition: Community
         Git Commit Hash: a8ad9b7d3aa53d0181422d2b22fa8d57b7d56db1
         Git Branch: master
         UTC Build Time: 2021-06-05 07:04:28
         GoVersion: go1.16.4
         Race Enabled: false
         TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
         Check Table Before Drop: false 
        ```

    - TiCDC version (execute `cdc version`):

        ```
        Release Version: v5.0.0-master-dirty  (with new owner)
        Git Commit Hash: fcd55523956572d14ac8a307ca69cacc006e5578
        Git Branch: master
        UTC Build Time: 2021-06-07 12:56:01
        Go Version: go version go1.16.4 linux/amd64
        Failpoint Build: false
        ```

**Comment by leoppro** [comment]
This is currently an expected behavior, and users can mitigate this by manually triggering scheduling
