### ISSUE TITLE
new_owner:  The process memory is still high after remove all changefeed.

### ISSUE THREAD

**Issue by asddongmen** [pingcap/ticdc#1992]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
3 TiKV, 3 TiDB, 3 PD, and 3 TiCDC are deployed on three different servers.

```shell
# Test flow:
# -> Set const NewReplicaImpl = true
# -> build master TiCDC
# -> patch the cluster
# -> drop database tpcc (if exist)
# -> Reset the status of the TiCDC cluster
# -> create 30 changefeed at begin (--sink-uri="blackhole://")
# -> write data into TiDB: tiup bench tpcc -H 172.16.6.125 -P 4000 -D tpcc100 --warehouses 100  prepare
# -> Gradually increase the number of changefeed, increasing by 10 each time
# -> Stop the test after 30 minutes.
```
Stop writing to upstream TiDB, and execute `cdc cli unsafe reset`, then drop `tpcc100` in tidb, but the process memory is still high.
![1623217771(1)](https://user-images.githubusercontent.com/20351731/121300554-91175680-c929-11eb-91f2-d195a610e84f.jpg)

2. What did you expect to see?

When there is no changefeed, memory consumption will drop to a low point.

3. What did you see instead?

The process memory is still high.

4. Versions of the cluster

   - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
         Release Version: v5.1.0-alpha-167-ga8ad9b7d3
         Edition: Community
         Git Commit Hash: a8ad9b7d3aa53d0181422d2b22fa8d57b7d56db1
         Git Branch: master
         UTC Build Time: 2021-06-05 07:04:28
         GoVersion: go1.16.4
         Race Enabled: false
         TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
         Check Table Before Drop: false 
        ```

    - TiCDC version (execute `cdc version`):

        ```
        Release Version: v5.0.0-master-dirty  (with new owner)
        Git Commit Hash: fcd55523956572d14ac8a307ca69cacc006e5578
        Git Branch: master
        UTC Build Time: 2021-06-07 12:56:01
        Go Version: go version go1.16.4 linux/amd64
        Failpoint Build: false
        ```

**Comment by overvenus** [comment]
We have optimized memory in the latest release, see https://github.com/pingcap/ticdc/issues/2553
