### ISSUE TITLE
new_owner: contents of /debug/info is changed, likely a compatibility bug

### ISSUE THREAD

**Issue by overvenus** [pingcap/ticdc#2015]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

BR CI fails with TiCDC release-5.1

![image](https://user-images.githubusercontent.com/2150711/121484427-c8f1cd00-ca01-11eb-802e-ef361ad3b46d.png)

2. What did you expect to see?

There should be CheckpointTs in "debug/info".

3. What did you see instead?

No CheckpointTs

4. Versions of the cluster

release-5.1

**Comment by ben1009** [comment]
temp solution: ci will use `checkpoint-ts` instead to unblock the testing process, will fix the compatibility issue later from cdc side.
