### ISSUE TITLE
tiup cluster v1.4.0 edit-config cannot modify cdc.gc-ttl  while no document record which tiup cluster can support this parameter

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#2068]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- tiup cluster edit-config to modify cdc.gc-ttl

2. What did you expect to see?

- The modification is successful. Or there's document tells users which version support to modify cdc.gc-ttl

3. What did you see instead?

- 
![hYct0Eue3j](https://user-images.githubusercontent.com/78345569/122202151-54ba9c00-cecf-11eb-9360-21f0228e880d.png)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
       v5.1.0-20210615

        ```

    - TiCDC version (execute `cdc version`):

        ```
       v5.1.0-20210615
        ```

**Comment by amyangfei** [comment]
Is is supported since tiup 1.5.x

**Comment by overvenus** [comment]
The latest TiUP supports change gc-ttl. Closed.
