### ISSUE TITLE
Data inconsistent between tidb(upstream) and mysql 8.0(downstream)

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#2131]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Create changefeed with filter to sync coms.PK tables.
    
![image](https://user-images.githubusercontent.com/78345569/123026004-0e54c800-d40e-11eb-9c3c-033ca81b2a08.png)

- Using lightning import SQL workload to TiDB, DDL and DML, table count: 1427
- Check mysql downstream(8.0.25 MySQL Community Server) ,all tables are synced, then check if data consistent,

2. What did you expect to see?

- data consistent

3. What did you see instead?

- data inconsistent for same tables:   
   TiDB:
![image](https://user-images.githubusercontent.com/78345569/123026317-858a5c00-d40e-11eb-9eac-a8fd3554f141.png)
   MYSQL:
![Uploading image.png…]()

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        Release Version: v5.1.0
Edition: Community
Git Commit Hash: 4ca5d03fbe2fe1d2106a29a38b4c99be66b36eb1
Git Branch: heads/refs/tags/v5.1.0
UTC Build Time: 2021-06-17 07:24:39
GoVersion: go1.16.4

        ```

    - TiCDC version (execute `cdc version`):

        ```
        [release-version=v5.1.0] [git-hash=a91a10bb5cd52ee22e56217402003a596a1b5f2b] [git-branch=heads/refs/tags/v5.1.0] [utc-build-time="2021-06-17 07:20:55"]
        ```

**Comment by Tammyxia** [comment]
Checked other PK_TCOLLATIONxxx table(PK_TCOLLATION10171,PK_TCOLLATION10198)also has data inconsistent.

**Comment by Tammyxia** [comment]
More tables are inconsistent， include: PK_SNPRE10111, PK_S_MULTI_39, PK_TCOLLATION3965STROBJSTROBJ

**Comment by amyangfei** [comment]
Some questions:
- How is the data compared between upstream and downstream
- Could you please provide the table schema of other inconsistent tables

**Comment by Tammyxia** [comment]
PK_RP9458 , PK_SIGNED_10091, PK_AUTO_INCREMENT9098, PK_GCOL_STORED9993, PK_MULTI_COL2328STROBJSTROBJ, PK_NO_PRECISION10104,  PK_PRECISION10060 are consistent, while PK_RCP9310, PK_10210,  PK_CCOLLATION10360, PK_DATE6, PK_HP9160 are inconsistent.

**Comment by Tammyxia** [comment]
Answer:
  Check tool: sync-diff and my eyes.
  Many tables are inconsistent, I just record them and classifited the type with name.
  No, I think we can focus on the tidb compatibility first.

**Comment by overvenus** [comment]
Could you show your changefeed settings?

**Comment by Tammyxia** [comment]
Close it  now since table PK_xxx10170 is consistent, and sync-diff is hard to check thousands of different schema.
