### ISSUE TITLE
"tiup ctl:v5.0.2 cdc cli changefeed create" failed "unknown flag: --sink-uri"

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#2146]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

-  tiup ctl:v5.1.0 cdc cli create changefeed failed:

![jZ2KFKJezK](https://user-images.githubusercontent.com/78345569/123217174-e1331300-d4fc-11eb-9ec8-04b12f0a7bcc.png)

- "tiup ctl:v5.0.2 cdc cli changefeed create --pd=http://172.16.6.195:2379 --sink-uri='blackhole://'   --changefeed-id='test-bl-2' --config /home/changefeed.toml" also failed with error message "unknown flag: --sink-uri"

- While tiup cdc cli is OK with the same parameters. "# tiup  cdc cli changefeed create --pd=http://172.16.6.195:2379 --sink-uri='blackhole://'   --changefeed-id='test-bl-1' --config /home/changefeed.toml"

2. What did you expect to see?

3. What did you see instead?
"tiup ctl:v5.0.2 cdc cli changefeed create xxx" failed to execute while " tiup  cdc cli changefeed create" succesfully executing.
4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
       5.1.0 06-23
        ```

    - TiCDC version (execute `cdc version`):

        ```
        5.1.0 06-23
        ```

**Comment by amyangfei** [comment]
Use 
`tiup ctl:v5.0.2 cdc changefeed list --pd=http://172.16.6.134:12379`
or 
`tiup cdc cli changefeed list --pd=http://172.16.6.134:12379`

`tiup ctl cdc` contains `cdc cli`

**Comment by amyangfei** [comment]
The command is not used properly, not a bug.
