### ISSUE TITLE
Metrics labels should not contain ID, table name or other unbounded sets of values

### ISSUE THREAD

**Issue by overvenus** [pingcap/ticdc#2183]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

Running a changefeed which captures 20k tables produces large metric records.

We should not put ID and table names in metrics labels.

> CAUTION: Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.
>
> https://prometheus.io/docs/practices/naming/#labels

Here is a list of problematic metrics

- [x] ticdc_kvclient_region_token
 * not monitored
- [x] ticdc_sorter_consume_count
 *  no need to update
- [x] ticdc_sorter_event_count
 * no need to update
- [x] ticdc_sorter_flush_count_histogram
 * no need to update
- [x] ticdc_sorter_merge_count_histogram
 * no need to update
- [x] ticdc_sorter_merger_start_ts_gauge
 * not monitored
- [x] ticdc_sorter_resolved_ts_gauge
 * not monitored
- [x] ticdc_kvclient_channel_size
 * not monitored
- [x] ticdc_processor_table_memory_consumption
   - [x] histogram
   - [x] update grafana
     - [x] Processor Memory Consumption Per Capture
     - [x] Processor Memory Consumption Per Table -> Per Capture 
- [x] ticdc_processor_table_resolved_ts
  - [x] Table Resolved ts 
- [x] ticdc_puller_event_chan_size
   - [x] histogram
   - [x] update grafana 
     - [x] Puller buffer size
- [x] ticdc_puller_output_chan_size
   - [x] histogram
   - [x] update grafana 
     - [x] Puller buffer size 
- [x] ticdc_puller_resolved_ts
 * not monitored
- [x] ticdc_puller_txn_collect_event_count
 * no need to update

**Any unbounded sets of labels should be avoided, and use other ways to record critical metrics.**

For above metrics, we should

* Remove the `table` and other labels that have high cardinality.
* Use sampling.

Eg. we can rewrite `ticdc_processor_table_memory_consumption` to 

```go
// Sampling, turn gague/counter into histogram.
tableMemoryGauge = prometheus.NewGaugeVec(
	prometheus.GaugeOpts{
		Namespace: "ticdc",
		Subsystem: "processor",
		Name:      "table_memory_consumption",
		Help:      "estimated memory consumption for a table after the sorter",
	}, []string{"changefeed", "capture", "table"})

tableMemoryHistogram = prometheus.NewHistogramVec(
	prometheus.HistogramOpts{
		Namespace: "ticdc",
		Subsystem: "processor",
		Name:      "table_memory_consumption",
		Help:      "estimated memory consumption for a table after the sorter",
	}, []string{"changefeed", "capture"})
```

2. What did you expect to see?

A smaller metric record.

3. What did you see instead?

A large metrics records, 28MB. [metrics.tar.gz](https://github.com/pingcap/ticdc/files/6730807/metrics.tar.gz)

4. Versions of the cluster

v5.0.2/v4.0.13

**Comment by Tammyxia** [comment]
Maybe prometheus OOM has relationship with this issue :
[Tue Jun 29 00:49:03 2021] Out of memory: Kill process 67251 (prometheus) score 60 or sacrifice child
[Tue Jun 29 00:49:03 2021] Killed process 67252 (run_prometheus.) total-vm:113176kB, anon-rss:188kB, file-rss:436kB, shmem-rss:0kB

**Comment by 3AceShowHand** [comment]
* make clear of all Prometheus metrics definition and usage in TiCDC
* optimize it
* adjust Grafana if necessary.

**Comment by 3AceShowHand** [comment]
`memBufferSizeGauge` is not used.

**Comment by 3AceShowHand** [comment]
`outputChanSizeGauge` is not used.

**Comment by 3AceShowHand** [comment]
`ticdc_processor_table_memory_consumption` / `ticdc_processor_table_resolved_ts` are metrics targeting on tables, maybe we have to keep it at table level.

**Comment by 3AceShowHand** [comment]
` ticdc_kvclient_region_token` is not in grafana and alertmanager, maybe we should remove it ?

**Comment by 3AceShowHand** [comment]
@liuzix 
`ticdc_sorter_merger_start_ts_gauge` is not in grafana and alertmanager, should we add related monitoring?

**Comment by 3AceShowHand** [comment]
for timestamp-related metrics, since it's such a critical metrics, I think it would prefer to use the gauge for timely.
