### ISSUE TITLE
TiCDC supports synchronization of user information tables

### ISSUE THREAD

**Issue by hi-rustin** [pingcap/ticdc#2192]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently TiCDC filters all system tables. But in the master-slave scenario we want to synchronize the user information table so that after the master-slave switch there will be no error that the user cannot login.

**Describe the feature you'd like:**
TiCDC supports synchronization of user information tables

**Describe alternatives you've considered:**

N/A

**Teachability, Documentation, Adoption, Migration Strategy:**
N/A

**Comment by hi-rustin** [comment]
This is a feature request from tidbclould that has the following problems if implemented:

- We need to ensure user table compatibility because tidb's `mysql.user` table will be inconsistent due to version differences.
- Because cdc supports filtering rules, it is possible to synchronize only some of the dbs or tables. So also consider filtering out the permission information of related tables when synchronizing user permissions.

Off-line discussion: Considering this complex logic, we decided to develop a special version of cdc for tidbcloud. tidbcloud will ensure that upstream and downstream permissions are consistent and that all tables are synchronized. This way, the above mentioned problems do not exist.

cc: @amyangfei  @overvenus  @leoppro 

Do you have any questions about this feature request? If not I'm ready to develop it (already briefly tested the feature and it works), also which branch do I need to commit the code to?

**Comment by overvenus** [comment]
Just a reminder, we do need to pay attention to `mysql.user` privilege requirements. 

> which branch do I need to commit the code to?

Please choose "cloud-cdc-5.0" as your PR base branch.

**Comment by hi-rustin** [comment]
> Just a reminder, we do need to pay attention to `mysql.user` privilege requirements.

@overvenus Could you please provide more details?

**Comment by hi-rustin** [comment]
/close

by https://github.com/pingcap/ticdc/pull/2218
