### ISSUE TITLE
workerpool.(*mergedContext).Done creates too many goroutines

### ISSUE THREAD

**Issue by overvenus** [pingcap/ticdc#2211]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

Capturing 6k tables, go runtime trace shows workerpool.(*mergedContext).Done creates 105k goroutines, this is clearly not expected, it should be optimized.

```
Goroutines:
golang.org/x/sync/errgroup.(*Group).Go.func1 N=81848
runtime.gcBgMarkWorker N=38google.golang.org/grpc/internal/transport.(*http2Client).reader N=27802
github.com/pingcap/ticdc/cdc.(*oldProcessor).addTable.func2.5 N=6672
github.com/pingcap/ticdc/pkg/workerpool.(*mergedContext).Done.func1 N=1056480
github.com/pingcap/ticdc/cdc.(*oldProcessor).addTable.func2.4 N=6672
runtime.bgsweep N=1google.golang.org/grpc/internal/transport.(*http2Client).keepalive N=27798
github.com/pingcap/ticdc/pkg/notify.(*Receiver).signalTickLoop.func1 N=13381
google.golang.org/grpc/internal/transport.newHTTP2Client.func3 N=27802
net/http.(*conn).serve N=2
```

2. What did you expect to see?

No 105k goroutines.

3. What did you see instead?

105k goroutines.

4. Versions of the cluster

v5.0.3

**Comment by amyangfei** [comment]
will be fixed by #2201
