### ISSUE TITLE
CDC granfana: Old Value Cache Hit has negative numbers

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#2227]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- CDC granfana ->TiKV -> Old Value Cache Hit has negative numbers.
![image](https://user-images.githubusercontent.com/78345569/124551258-740c6f80-de64-11eb-81e9-796920e4dbb1.png)

2. What did you expect to see?

3. What did you see instead?

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        5.0.2
        ```

    - TiCDC version (execute `cdc version`):

        ```
        5.0.2
        ```

**Comment by overvenus** [comment]
This is intended, we explicitly prefix a `-` in expr.
