### ISSUE TITLE
CDC cloud:  workload 6w table count, changefeed cannot work at all

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#2228]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- BR restore to upstream tidb with 6w tables.
- 2xCDC 128GB memory
- Create a changefeed, sink-uri is blackhole.

2. What did you expect to see?

- Changefeed can sync data, at least checkpoint can move on when upstream has not any I/O.

3. What did you see instead?

- Changefeed checkpoint has not any changing after creating.
- cdc log has etcd error because etcd is full.
- Other command such as "changefeed remove" cannot work, CDC don't reponse any command. 

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        5.0.2
        ```

    - TiCDC version (execute `cdc version`):

        ```
        5.0.2
        ```

**Comment by Tammyxia** [comment]
Set it as critical issue because now users need this scenario to sync data.

**Comment by overvenus** [comment]
I am going to close this issue, 
1. It's far beyond than the current TiCDC capability and we plan to support this in the next few months.
2. It is not a report bug, more like a feature request.
3. We are tracking the feature request in project [Capturing 60K Tables](https://github.com/pingcap/ticdc/projects/12 )
