### ISSUE TITLE
changefeed info can't be removed by changefeed remove command

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#2234]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

   In some users' scenario, a stopped changefeed can't be removed by `changefeed remove` command.

   ref: https://asktug.com/t/topic/68992

2. What did you expect to see?

    Changefeed can be removed

3. What did you see instead?

    Changefeed can't be removed, even after TiCDC servers are restarted, the changefeed still can't be removed.

    Other information, some users report restart TiKV could work. Some user report there exists accessibility problem to downstream Kafka.

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        v4.0.11
        ```

    - TiCDC version (execute `cdc version`):

        ```
        v4.0.11 or v4.0.13
        ```

**Comment by amyangfei** [comment]
It could have been fixed by https://github.com/pingcap/ticdc/pull/2471

**Comment by overvenus** [comment]
#2471 is merged, free feel to reopen if it happens again.
