### ISSUE TITLE
CDC cloud: run server error CDC:ErrGetDiskInfo permission denied

### ISSUE THREAD

**Issue by ben1009** [pingcap/ticdc#2245]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
create changefeed with tidb as sink, go-ycsb load from upstream
2. What did you expect to see?
work normaly
3. What did you see instead?

~`run server: owner exited with error: rpc error: code = ResourceExhausted desc = trying to send message larger than max (2376980 vs. 2097152)`~, let's track the issue in #2190,

 from log 

`[ERROR] [server.go:129] ["run server"] [error="[CDC:ErrGetDiskInfo]open /tidb-data/cdc-18303/tmp/cdc_data/file.test: permission denied\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20201126102027-b0a155152ca3/errors.go:174 `

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
         5.0.0
        ```

    - TiCDC version (execute `cdc version`):

        ```
       Release Version: v5.0.2-63-g9300b05-dirty
      Git Commit Hash: 9300b05ceec2c4811198416a5d21e9f4910deddd
      Git Branch: HEAD
      UTC Build Time: 2021-07-07 07:24:23
      Go Version: go version go1.16.5 darwin/amd64
      Failpoint Build: false
        ```

**Comment by overvenus** [comment]
This is a duplicate with https://github.com/pingcap/ticdc/issues/2190, let's force on the `permission denied` error.

**Comment by 3AceShowHand** [comment]
this happens on a temporary patch version, workaround by changefeed dir permission, can not reproduce. 

close now,
