### ISSUE TITLE
Solve sink failure interrupting replication in Old Owner

### ISSUE THREAD

**Issue by liuzix** [pingcap/ticdc#2295]
Irresponsive downstreams will block the owner until the operation times out. For example, if the Kafka broker is down and the owner tries to send a checkpoint event, the owner would not be able to do ANYTHING until the Kafka sink has timed out (if ever). This will only happen in the old owner. 

# Action item

- [x] Back port `asyncSink` to the old owner
- [x] Make old owner's DDL execution asynchronous (in `changefeed.go`)

**Comment by amyangfei** [comment]
This issue is finished
