### ISSUE TITLE
cdc cli changefeed create --start-ts does not work properly and may lead to data loss

### ISSUE THREAD

**Issue by overvenus** [pingcap/ticdc#2303]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

TiCDC cli creates a changefeed that does not use the start-ts specified in command line. It leads to data loss.

![image](https://user-images.githubusercontent.com/2150711/125928254-3d21667f-dbe7-4ec1-a263-350320139cae.png)

Note that the start-ts in command line is invalid and it points to 1975-02-25 15:14:19.597000.

```
mysql> select tidb_parse_tso(426318359552065537); # start-ts in cli output

+------------------------------------+
| tidb_parse_tso(426318359552065537) |
+------------------------------------+
| 2021-07-14 23:11:20.469000         |
+------------------------------------+

mysql> select tidb_parse_tso(42610054816776198); # start-ts in command line

+-----------------------------------+
| tidb_parse_tso(42610054816776198) |
+-----------------------------------+
| 1975-02-25 15:14:19.597000        |
+-----------------------------------+
```

2. What did you expect to see?

  a. create a changefeed with a start-ts specified in command line.
  b. report warnings about invalid start-ts. 

3. What did you see instead?

A wrong changefeed is created and it leads to data loss. 

4. Versions of the cluster

v5.0.1

**Comment by amyangfei** [comment]
Strange, the `start-ts` should be checked against `GC safepoint`, what dos invalid `start-ts` means

**Comment by overvenus** [comment]
> Strange, the `start-ts` should be checked against `GC safepoint`, what does **invalid** means?

Sorry, I mean the ts is way behind TiDB gc safepoint.

**Comment by overvenus** [comment]
![image](https://user-images.githubusercontent.com/2150711/126254559-48a02f99-f573-4d01-bd24-28a1e554b93c.png)

@liuzix finds that there is an unexpected character ‘c2 a0’ before "--start-ts”. It may cause this issue.

**Comment by asddongmen** [comment]
It seems that any char before a flag will cause this error.!
![2021721-18274](https://user-images.githubusercontent.com/20351731/126474797-7bae5664-4855-441c-b6ae-69db027be08d.png)

**Comment by hi-rustin** [comment]
We can use `cobra.NoArgs` to report this error explicitly.
