### ISSUE TITLE
log heap profile in TiCDC when memory usage exceeds threshold

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#2307]
## Feature Request

**Is your feature request related to a problem? Please describe:**

TiCDC has heavy usage with memory, it could store large amount of raw kv events, unpacked data, table schema information, etc. There exist OOM risks in many scenarios. We need some ways to help to diagnose memory usage when OOM happens. However TiCDC lacks a memory dump mechanism when OOM happens.

**Describe the feature you'd like:**

Log heap profile in TiCDC when memory usage exceeds threshold.

**Comment by overvenus** [comment]
Dup with https://github.com/pingcap/ticdc/issues/1685 ?

**Comment by amyangfei** [comment]
duplicated with #1685
