### ISSUE TITLE
CDC v4.0.14: unified sort dir has much more data than the real incremental data size

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#2374]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- 2x CDC server, 188GB mem; 2x changefeed: 1x cf sink-uri=tidb, 1x cf sink-uri=kafka
- Pause the 2 changfeeds.
- Load data to upstream TiDB: ./bin/go-ycsb load mysql -P ./workloads/oncall2929 -p mysql.host=172.16.xxx -p mysql.port=4000 -p operationcount=5000000 -p autocommit=1 --threads=200 -p databasename=test123 -p tablename=test111
- Check database test123 has 800G data size, then stop to load data.
- Resume the 2 changefeeds.

2. What did you expect to see?

- unified sort  data size less than 1TB.

3. What did you see instead?

- The first incremental data scan ends in 20:04, you can see unified sorter on disk data size is about 2TB
![image](https://user-images.githubusercontent.com/78345569/126954102-8f322a48-9654-4a11-8f59-1911a40d17ab.png)
![image](https://user-images.githubusercontent.com/78345569/126957259-74381f77-2982-4096-8624-662d8b708985.png)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        v4.0.14
        ```

    - TiCDC version (execute `cdc version`):

        ```
        v4.0.14
        ```

**Comment by Tammyxia** [comment]
re-rerun this test,  but incremental data size is 400GB, we can see unified sorter on disk size is about 900GB, it's twice than the real data size.
![image](https://user-images.githubusercontent.com/78345569/126960735-346c7ab7-f84f-4b97-86b9-4c2f74da6539.png)

**Comment by asddongmen** [comment]
There are some issue that have similar phenomena.
#1843 
#1642

**Comment by overvenus** [comment]
This issue may relates to https://github.com/pingcap/ticdc/issues/2375

**Comment by overvenus** [comment]
Closed in favor of #1843
