### ISSUE TITLE
Which command is the recommended to manage TiCDC, tiup cdc cli or tiup ctl:{cluster_version} cdc?

### ISSUE THREAD

**Issue by zhenjiaogao** [pingcap/ticdc#2477]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

2. What did you expect to see?
There are two ways to manage TiCDC clusters, tiup cdc cli and tiup ctl:{cluster_version} cdc

3. What did you see instead?
Only one command to manage the ticdc cluster, tiup cdc cli or tiup ctl:{cluster_version} cdc

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        (paste TiDB cluster version here)
        ```

    - TiCDC version (execute `cdc version`): 

        ```
        v5.1.1
        ```

**Comment by 3AceShowHand** [comment]
shall we solve this problem in the TiUP?

**Comment by hi-rustin** [comment]
I also feel this is a usage issue with tiup? 

cc: @overvenus @lucklove What do you think?

**Comment by overvenus** [comment]
With tiup, we recommend the later one, `tiup ctl:{cluster_version} cdc`.

**Comment by hi-rustin** [comment]
@zhenjiaogao With overvenus 's answer, do you have any more questions?
