### ISSUE TITLE
CDC cloud: open /var/lib/ticdc/tmp/sorter/sort-1-2728063.tmp: too many open files

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#2550]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- There are 8 CDC servers, each has  vcpu36c mem72g , 1 changefeed, 6w tables.
- Restart all CDC node:  kubectl delete pod  db-ticdc-0 db-ticdc-1 db-ticdc-2 db-ticdc-3 db-ticdc-4 db-ticdc-5 db-ticdc-6 db-ticdc-7 --kubeconfig=/etc/kubernetes/cluster1.conf -n tidb60070

2. What did you expect to see?

- All cdc node can recover and continue to sync data.

3. What did you see instead?

- Changefeed don't sync data anymore with  error:
  bash-5.0#  /cdc cli --ca=/var/lib/ticdc-tls/ca.crt --cert=/var/lib/ticdc-tls/tls.crt --key=/var/lib/ticdc-tls/tls.key changefeed list --pd=https://db-pd:2379
[
  {
    "id": "replication-task-60045",
    "summary": {
      "state": "normal",
      "tso": 426977045510095067,
      "checkpoint": "2021-08-12 17:09:27.992",
      "error": {
        "addr": "db-ticdc-5.db-ticdc-peer.tidb60070.svc:8301",
        "code": "CDC:ErrUnifiedSorterIOError",
        "message": "[CDC:ErrUnifiedSorterIOError]unified sorter IO error. Make sure your sort-dir is configured correctly by passing a valid argument or toml file to `cdc server`, or if you use TiUP, review the settings in `tiup cluster edit-config`. Details: open /var/lib/ticdc/tmp/sorter/sort-1-2728063.tmp: too many open files"
      }
    }
  }
]

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
       4.0.14
        ```

    - TiCDC version (execute `cdc version`):

        ```
        4.0.14 cloud 
         Release Version: v4.0.14-42-gc24e30f
         Git Commit Hash: c24e30f1a26b3de97443254b6c178acb613c2263
         Git Branch: HEAD
         UTC Build Time: 2021-08-11 06:03:32
         Go Version: go version go1.16.4 linux/amd64
         Failpoint Build: false
        ```

**Comment by overvenus** [comment]
Dup with https://github.com/pingcap/ticdc/issues/2698.
