### ISSUE TITLE
4.0.14 hotfix issue: After downstream kafka server recovering, the related changefeed don't recover automatically

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#2552]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- 2 changefeed, 1 has sink-uri=mysql, the other has sink-uri=kafka
- sysbench prepare write DDL
- stop kafka server 15minutes
- start kafka server

2. What did you expect to see?

- kafka changefeed can recover automatically

3. What did you see instead?

- kafka changefeed is interrupted persistently.
- manually pause this kafka changefeed, then resume it, it can recover.

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        4.0.14
        ```

    - TiCDC version (execute `cdc version`):

        ```
Release Version: v4.0.14-20210816
Git Commit Hash: 2f7548916d62db65466af774fc44fe07d4cb5c03
Git Branch: heads/refs/tags/v4.0.14-20210816
UTC Build Time: 2021-08-16 08:38:12
Go Version: go version go1.13 linux/amd64
Failpoint Build: false

        ```

**Comment by amyangfei** [comment]
Closed by #2556
