### ISSUE TITLE
campaign owner failed due to can not find lease info

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/ticdc#2562]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

* only 1 capture server, but campaign owner failed.

<img width="2557" alt="Lark20210818-142716" src="https://user-images.githubusercontent.com/7138436/129848582-2f351bef-d184-48f5-9863-65254a9a1363.png">

2. What did you expect to see?

* owner returned

3. What did you see instead?

* campaign owner failed.

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        (paste TiDB cluster version here)
        ```

    - TiCDC version (execute `cdc version`):

        ```
        v4.0.14
        ```

[cdc.log](https://github.com/pingcap/ticdc/files/7005134/cdc.log)

**Comment by overvenus** [comment]
Closed as no further reports, feel free to reopen if it happens again.
