### ISSUE TITLE
changefeed status expected stopped or ERROR not failed when downstream tidb service closed

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#2564]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- 1x changefeed, both upstream and downstream are tidb cluster.
- Close downstream tidb server: tiup cluster stop xxx
- Check chagefeed status.

2. What did you expect to see?

- changefeed status becomes stopped or ERROR， since changefeed can be recover in this scenario.

3. What did you see instead?

- changefeed status becomes failed
"id": "replication-task-22",
"summary": {
"state": "failed",
"tso": 426609957701681153,
"checkpoint": "2021-07-27 20:10:39.133",
"error": {
"addr": "172.16.6.32:8300",
"code": "CDC-owner-1001",
"message": "fail to open MySQL connection: [CDC:ErrMySQLConnectionError]dial tcp 172.16.6.31:4000: connect: no route to host"

- According to this doc: https://docs.pingcap.com/tidb/stable/manage-ticdc, failed means: "Failed: The replication task fails. Due to some unrecoverable errors, the replication task cannot resume and cannot be recovered. The changefeed in this state does not block GC operations." , so doc definitition is not match with changefeed real behavior.

- The impact to user is, though failed changefeed cannot recover, which means CDC don't support downstream unvailable for a while.

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
         4.0.14
        ```

    - TiCDC version (execute `cdc version`):

        ```
        4.0.14
        ```

**Comment by Tammyxia** [comment]
Related issue: https://github.com/pingcap/ticdc/issues/2390

**Comment by overvenus** [comment]
Closed in favor of #2390
