### ISSUE TITLE
list partition information lost when replicating DDL

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#2565]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

   1. Setup a TiDB cluster 5.1 with TiCDC, create a changefeed
   2. Execute the following statements in upstream

```
mysql root@127.0.0.1:test1> set @@session.tidb_enable_list_partition = ON;

mysql root@127.0.0.1:test1> CREATE TABLE employees (
                           ->      id INT NOT NULL,
                           ->      hired DATE NOT NULL DEFAULT '1970-01-01',
                           ->      store_id INT,
                           ->      primary key (store_id)
                           ->  )
                           ->  PARTITION BY LIST (store_id) (
                           ->      PARTITION pNorth VALUES IN (1, 2, 3, 4, 5),
                           ->      PARTITION pEast VALUES IN (6, 7, 8, 9, 10),
                           ->      PARTITION pWest VALUES IN (11, 12, 13, 14, 15),
                           ->      PARTITION pCentral VALUES IN (16, 17, 18, 19, 20)
                           ->  );
```

2. What did you expect to see?

   The same table is created in downstream

3. What did you see instead?

   The table structure in downstream is as follows, list partition is lost

```
***************************[ 1. row ]***************************
Table        | employees3
Create Table | CREATE TABLE `employees3` (
  `id` int(11) NOT NULL,
  `hired` date NOT NULL DEFAULT '1970-01-01',
  `store_id` int(11) NOT NULL,
  PRIMARY KEY (`store_id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        5.1.0

    - TiCDC version (execute `cdc version`):

        5.1.0

5. Addition

   Note this is caused by list partition works only by setting **session** variable `tidb_enable_list_partition` to `ON`. TiCDC should execute the list partition DDL with this session variable `ON`. If TiCDC supports this feature, we should pay attention to several points

   1. Only TiDB has this session variable, if we execute `set @@session.tidb_enable_list_partition = ON` in MySQL, we will meet error `(1193, "Unknown system variable 'tidb_enable_list_partition'")`
   2. We should pay attention to the privilege requirement for setting a session variable. (Maybe no special privilege needed, since it is a session variable)

**Comment by Tammyxia** [comment]
list partition is 5.2.0 GA feature, this issue will block v5.2.0 release.

**Comment by cyliu0** [comment]
list partition will not GA in 5.2.0.

**Comment by Tammyxia** [comment]
Both upstream and downstream enable  list partition first, then create changefeed, sync list partition table can be successful, and data consistency is pass.
