### ISSUE TITLE
changefeed meet ErrMetaListDatabases

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/ticdc#2646]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

go-tpc workload, prepare data for 1 hour, then run for another 2 hours, but the changefeed meet error, the task failed without any data synced.

2. What did you expect to see?

changefeed in normal state.

3. What did you see instead?

![Lark20210826-131736](https://user-images.githubusercontent.com/7138436/130905713-85a45d0d-b16d-4441-a52b-7571b9eff63f.png)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        (paste TiDB cluster version here)
        ```

    - TiCDC version (execute `cdc version`):

        ```
        v5.2.0-nightly
        ```
[cdc-0.log](https://github.com/pingcap/ticdc/files/7051829/cdc-0.log)

**Comment by amyangfei** [comment]
Fixed by #2639
