### ISSUE TITLE
CDC cloud: changefeed don't work after all CDC restarted

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#2672]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- 8x CDC, 1x changefeed, k8s clould env.
- Modify CDC config log-file, then all CDC node restarted.
- Check changefeed status.

2. What did you expect to see?

- Changefeed works normally after initialization finished.

3. What did you see instead?

- Changefeed don't work after almost 2hours.
- 
![image](https://user-images.githubusercontent.com/78345569/131306414-4b92b5c0-556f-41b7-9d79-6a42815fdb18.png)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
       4.0.14
        ```

    - TiCDC version (execute `cdc version`):

        ```
        Release Version: 4.0.14
Git Commit Hash: bbfda297e0e5ddbfb5e3386938be50758c74bdbb
Git Branch: cloud-cdc-4.0
UTC Build Time: 2021-08-26 14:08:37
Go Version: go version go1.16.3 linux/amd64
Failpoint Build: false

        ```

**Comment by overvenus** [comment]
The changefeed is stopped by too many open file, it's the same as #2698 , closed.
