### ISSUE TITLE
gRPC initial window is too large that may cause OOM

### ISSUE THREAD

**Issue by overvenus** [pingcap/ticdc#2673]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

Capture 10k tables with ~90G incremental data using single CDC node.

heap profile: [profile.pb.gz](https://github.com/pingcap/ticdc/files/7075353/profile.pb.gz)

| gRPC client | flamegraph |
| -- | -- |
![image](https://user-images.githubusercontent.com/2150711/131310040-6426a48f-191e-49c5-b476-3663e703de1e.png) | ![image](https://user-images.githubusercontent.com/2150711/131310110-f43349ba-7189-4d89-963a-c83541a55c33.png)

2. What did you expect to see?

No OOM.

3. What did you see instead?

gRPC client consumes too many memory and cause OOM.

4. Versions of the cluster

v5.1.0

**Comment by overvenus** [comment]
This issue relates to https://github.com/pingcap/ticdc/issues/2553

**Comment by amyangfei** [comment]
Data accumulated in kv client, it may be caused by low throughput with gRPC message processing. Is there any goroutine dump during the test.

**Comment by overvenus** [comment]
> Data accumulated in kv client, it may be caused by low throughput of gRPC message processing. 

Yes, data accumulation is caused by unbalanced producing and consuming speed, in this case, we have a slow sorter (i/o bottleneck), kv client is much faster than the sorter. 


Also, after changing initial window size to 64KB and initial conn window size to 8MB, the OOM disappeared.


```diff
-	grpcInitialWindowSize     = 1 << 26 // 64 MB The value for initial window size on a stream
-	grpcInitialConnWindowSize = 1 << 27 // 128 MB The value for initial window size on a connection
+	grpcInitialWindowSize     = 65535 // 64 KB The value for initial window size on a stream
+	grpcInitialConnWindowSize = 1 << 23 // 8 MB The value for initial window size on a connection
```

**Comment by overvenus** [comment]
> Is there any CPU profile dump during the test.

[profile.pb.gz](https://github.com/pingcap/ticdc/files/7076938/profile.pb.gz)

**Comment by lonng** [comment]
> > Data accumulated in kv client, it may be caused by low throughput of gRPC message processing. 
> 
> Yes, data accumulation is caused by unbalanced producing and consuming speed, in this case, we have a slow sorter (i/o bottleneck), kv client is much faster than the sorter. 
> 
> 
> Also, after changing initial window size to 64KB and initial conn window size to 8MB, the OOM disappeared.
> 
> 
> ```diff
> -	grpcInitialWindowSize     = 1 << 26 // 64 MB The value for initial window size on a stream
> -	grpcInitialConnWindowSize = 1 << 27 // 128 MB The value for initial window size on a connection
> +	grpcInitialWindowSize     = 65535 // 64 KB The value for initial window size on a stream
> +	grpcInitialConnWindowSize = 1 << 23 // 8 MB The value for initial window size on a connection
> ```
> 

Is there performance issue if we lower those values?
