### ISSUE TITLE
EtcdWorker cannot correctly handle the PD leader being killed

### ISSUE THREAD

**Issue by liuzix** [pingcap/ticdc#2674]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
- Kill the PD leader when CDC is running

2. What did you expect to see?
- That replication can automatically recover.

3. What did you see instead?
- The owner is stuck

**Comment by overvenus** [comment]
Refer to https://github.com/pingcap/ticdc/issues/3615.
