### ISSUE TITLE
CDC grafana: min tikv resolved ts lag time display 

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#2690]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Restart all tikv
- Check TiCDC grafana->TiKV, last 3 hours

2. What did you expect to see?

3. What did you see instead?
![image](https://user-images.githubusercontent.com/78345569/131465518-c41f11fa-4795-4978-abcd-b85cbc9a7436.png)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
       4.0.14
        ```

    - TiCDC version (execute `cdc version`):

        ```
        4.0.14 cloud
        ```

**Comment by Tammyxia** [comment]
5.4 nightly version also has similar problem:
![HXoxZTeVbw](https://user-images.githubusercontent.com/78345569/143983621-622ec730-7b4e-4dbb-abab-00c63f2af535.png)

while resolved tag is correct:
![image](https://user-images.githubusercontent.com/78345569/143983670-f91bd619-637e-4518-84b1-3de257a28a74.png)

 [PD] [release-version=v5.4.0-nightly]
 [git-hash=318f9ceddcb0a35a5a61a2121741a251c85064ec]

["Welcome to TiKV"]
["Git Commit Hash:   f0b253aac42b68eb2068a2890b448ef1cfbdd911"]

**Comment by overvenus** [comment]
Fixed by https://github.com/pingcap/ticdc/pull/3098
