### ISSUE TITLE
do we need overview of integration tests for better test experience?

### ISSUE THREAD

**Issue by maxshuang** [pingcap/ticdc#2705]
## Question
       
When I run integration tests of ticdc for the first time, I notice we only get a Readme file with only preparations/running sectors. It doesn't clearly point out what kind of integration test we already have, and the upstream and downstream components on which it relies pre test.
      
I think it will be better if we can maintain the overview of the integration tests, and make it easier and more clear for the new contributor.

**Comment by hi-rustin** [comment]
Yes, I think we need not only an overview, but probably a better script to help us download and run the relevant components and tests.

such as: https://github.com/rust-lang/rust/blob/master/x.py

**Comment by amyangfei** [comment]
Can reference ci script: 

https://github.com/PingCAP-QE/ci/blob/0168669f271712bcde92dff2603fcf962d90c69b/jenkins/pipelines/ci/ticdc/integration_test_common.groovy#L242-L279

**Comment by maxshuang** [comment]
> Yes, I think we need not only an overview, but probably a better script to help us download and run the relevant components and tests.
> 
> such as: https://github.com/rust-lang/rust/blob/master/x.py

I had already writed a script to download and complie the related binary on which we relayed locally. Under test.

**Comment by maxshuang** [comment]
I also find running integration tests locally is a terrible experience, because of it outputs too much debug infos and lack of a friendly sketch for  the result.  

Need  track some progress worked on it.
