### ISSUE TITLE
Too many logs: "synchronize is taking too long, report a bug" occupied a lot disk capacity

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#2706]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Workload: DML + 20 new creating tables.
- TiKV scale-in from 24 to 20. Total region 20w.

2. What did you expect to see?

3. What did you see instead?

- Owner node new generated 230+ cdc log in 20hours, each log file is 300MB, which occupied too much disk capacity.
- 
![image](https://user-images.githubusercontent.com/78345569/131621684-2ca19cf8-ff18-4d2a-b082-54fa249f7184.png)
![image](https://user-images.githubusercontent.com/78345569/131622260-13c13cd7-2f16-41e4-912e-392cf328b741.png)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        4.0.14
        ```

    - TiCDC version (execute `cdc version`):

        ```
       4.0.14 cloud
        ```

**Comment by liuzix** [comment]
This seems to be the exact problem solved by #2078

**Comment by overvenus** [comment]
@liuzix Can we set the level to debug or reduce frequency? In this case, it takes lots of CPU and IO and may block the entire TiCDC process.

![image](https://user-images.githubusercontent.com/2150711/131945393-a51edf39-3dbe-439f-8394-c0acfe96b5e9.png)

**Comment by amyangfei** [comment]
ref: https://github.com/pingcap/ticdc/commit/d6ac981611b447c9ac8883904f7458edfc91768a

**Comment by overvenus** [comment]
@liuzix Please cherry-pick https://github.com/pingcap/ticdc/commit/d6ac981611b447c9ac8883904f7458edfc91768a to master branch, thanks!
