### ISSUE TITLE
test github action

### ISSUE THREAD

**Issue by ben1009** [pingcap/ticdc#2707]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        (paste TiDB cluster version here)
        ```

    - TiCDC version (execute `cdc version`):

        ```
        (paste TiCDC version here)
        ```

**Comment by ben1009** [comment]
Can't find any online and idle self-hosted or hosted runner in the current repository, account/organization that matches the required labels: 'ubuntu-latest'
Waiting for a self-hosted or a hosted runner to pickup this job...

**Comment by hi-rustin** [comment]
> Can't find any online and idle self-hosted or hosted runner in the current repository, account/organization that matches the required labels: 'ubuntu-latest'
> Waiting for a self-hosted or a hosted runner to pickup this job...

This means that our actions are under-resourced.

**Comment by ben1009** [comment]
> > Can't find any online and idle self-hosted or hosted runner in the current repository, account/organization that matches the required labels: 'ubuntu-latest'
> > Waiting for a self-hosted or a hosted runner to pickup this job...
> 
> This means that our actions are under-resourced.

	
 30 minutes ago
 Queued

**Comment by ben1009** [comment]
Resource not accessible by integration

**Comment by ben1009** [comment]
Organisation or User project
Generate a token from the Organisation settings or User Settings and add it as a secret in the repository secrets as MY_GITHUB_TOKEN

**Comment by ben1009** [comment]
![image](https://user-images.githubusercontent.com/1741864/131655934-c482c361-3e40-4a28-90c4-d31dadcd03fe.png)

done, close the issue
