### ISSUE TITLE
downstream exec DDL fail, but cdc has no detail warn/error log

### ISSUE THREAD

**Issue by maxshuang** [pingcap/ticdc#2755]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- setup upstream tidb cluster and downstream mysql,  create changefeed;
- upstream already has "test" database, but downstream not
- create a table of "test" in upstream
- use "./cdc cli changefeed query --pd=xxx --changefeed-id=xxx" to get the changefeed status
- we get error: 
    "error": {
      "addr": "127.0.0.1:8300",
      "code": "CDC:ErrProcessorUnknown",
      "message": "[CDC:ErrMySQLTxnError]Error 1146: Table 'test.test_cdc' doesn't exist"
    }

2. What did you expect to see?
        Expect to see the detail [WARNING] or [ERROR] level logs in cdc log, but only with [INFO] level logs which will be ignored if higher log level enabled in production environment.
 
3. What did you see instead?
 `
[2021/09/07 14:24:09.460 +08:00] [INFO] [mysql.go:213] ["execute DDL failed, but error can be ignored"] [query="create table test_cdc(id int primary key, col varchar(11))"] [error="[CDC:ErrMySQLTxnError]Error 1049: Unknown database 'test'"]
 [2021/09/07 14:24:09.460 +08:00] [INFO] [async_sink.go:137] ["Execute DDL succeeded"] [changefeed=simple-replication-task] [ignored=false] 
 `

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        v5.2.0
        ```

    - TiCDC version (execute `cdc version`):

        ```
       v5.2.0
        ```

**Comment by 3AceShowHand** [comment]
I think this is a known problem with the CDC default behavior, we need a discussion about it.
