### ISSUE TITLE
github action test failed due to log file name contains `invalid characters`

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#2805]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

```
Run actions/upload-artifact@v2
  with:
    name: logs
    path: /home/runner/work/ticdc/ticdc/docker/logs/*
    if-no-files-found: warn
  env:
    GOROOT: /opt/hostedtoolcache/go/1.16.4/x64
With the provided path, there will be 15 files uploaded
Error: Artifact path is not valid: /downstream-tikv2.log.2021-09-13-08:03:58.476397605. Contains character: ":". Invalid characters include: ",:,<,>,|,*,?.
```

test link: https://github.com/pingcap/ticdc/runs/3584188683

This is due to the limitation of `upload-artifact` https://github.com/actions/toolkit/blob/master/packages/artifact/docs/additional-information.md#non-supported-characters

2. What did you expect to see?

   CI runs successfully

3. Versions of the cluster

    - TiCDC version (execute `cdc version`):

        master@https://github.com/pingcap/ticdc/commit/5adb632229b578555f4e3600c9a54094403d9e58

**Comment by hi-rustin** [comment]
another case: https://github.com/pingcap/ticdc/pull/2807/checks?check_run_id=3595536238

**Comment by maxshuang** [comment]
@hi-rustin it's a flaky test that occur occasionally??  Do your have any suggestion to avoid this problem and move forward the pr?

**Comment by hi-rustin** [comment]
> @hi-rustin it's a flaky test that occur occasionally?? Do your have any suggestion to avoid this problem and move forward the pr?

Our GitHub Actions do not affect code merging. tide will not respect the GitHub Actions.

**Comment by hi-rustin** [comment]
Sorry I haven't been able to get started on that one!
