### ISSUE TITLE
Slow replication speed with large scale of regions

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#282]
## Feature Request

**Is your feature request related to a problem? Please describe:**

- set tikv config
```
[coprocessor]
region-max-keys = 6000
region-split-keys = 5000
```
- prepare data

```
sysbench oltp_write_only --create_secondary=off --rand-seed=$RANDOM --tables=1 --table-size=10000000 prepare
```

- start a CDC server and create a changefeed
- run sysbench
```
sysbench oltp_write_only --create_secondary=off --rand-seed=$RANDOM --tables=1 --table-size=10000000 run
```

**Describe the feature you'd like:**

- we found the replication speed is quite slow
- and the puller entry buffer will be filled up very fast

<img width="1372" alt="Screen Shot 2020-02-24 at 16 39 13" src="https://user-images.githubusercontent.com/1527315/75138050-3c47d080-5724-11ea-9398-b6bc8e4cda01.png">

<img width="1312" alt="Screen Shot 2020-02-24 at 16 37 58" src="https://user-images.githubusercontent.com/1527315/75138062-42d64800-5724-11ea-9467-1a27f62b5f4e.png">

<img width="1378" alt="Screen Shot 2020-02-24 at 16 37 37" src="https://user-images.githubusercontent.com/1527315/75138069-4669cf00-5724-11ea-94c9-8d7f52d47d56.png">

Besides found the span_frontier tasks too much CPU:

<img width="1063" alt="Screen Shot 2020-02-24 at 16 42 23" src="https://user-images.githubusercontent.com/1527315/75138222-a496b200-5724-11ea-8af2-a329ee9ab7f5.png">

profile file: http://139.219.11.38:8000/oitOt/pprof.cdc.samples.cpu.005.pb.gz

**Comment by GregoryIan** [comment]
@july2993 Please help to fix it ASAP

**Comment by amyangfei** [comment]
1. Have a benchmark on 5k, 10k, 50k span forward, and decide whether we need an optimization with the interval tree.
2. Compared with the interval tree used in CockroachDB

**Comment by july2993** [comment]
<details>
    <summary> bench code </summary>

```go
func toCMPBytes(i int) []byte {
    s := fmt.Sprintf("%09d", i)
    return []byte(s)
}

func BenchmarkSpanFrontier(b *testing.B) {
    tests := []struct {
        name string
        n    int
    }{
        {name: "5k", n: 5000},
        {name: "10k", n: 10_000},
        {name: "50k", n: 50_000},
        {name: "100k", n: 100_000},
    }

    for _, test := range tests {
        n := test.n

        b.Run(test.name, func(b *testing.B) {
            spans := make([]util.Span, 0, n)
            for i := 0; i < n; i++ {
                span := util.Span{
                    Start: toCMPBytes(i),
                    End:   toCMPBytes(i + 1),
                }
                spans = append(spans, span)
            }

            f := makeSpanFrontier(spans...)

            b.ResetTimer()

            for i := 0; i < b.N; i++ {
                f.Forward(spans[i%n], uint64(i))
            }
        })
    }
}
```
</details>

ticdc
```
goos: darwin
goarch: amd64
pkg: github.com/pingcap/ticdc/cdc/puller
BenchmarkSpanFrontier/5k-12        83764             15445 ns/op            9343 B/op        285 allocs/op
BenchmarkSpanFrontier/10k-12               71649             16007 ns/op           10063 B/op        308 allocs/op
BenchmarkSpanFrontier/50k-12               60201             19636 ns/op           11780 B/op        361 allocs/op
BenchmarkSpanFrontier/100k-12              51838             21521 ns/op           12362 B/op        380 allocs/op
PASS
ok      github.com/pingcap/ticdc/cdc/puller     8.160s
```
cockroach:
```
➜  span git:(master) ✗ GO111MODULE=off go test -run=^$ -bench=Ben -benchmem
goos: darwin
goarch: amd64
pkg: github.com/cockroachdb/cockroach/pkg/util/span
BenchmarkSpanFrontier/5k-12       360750              3177 ns/op             592 B/op         12 allocs/op
BenchmarkSpanFrontier/10k-12              343443              3849 ns/op             592 B/op         12 allocs/op
BenchmarkSpanFrontier/50k-12              289003              4134 ns/op             592 B/op         12 allocs/op
BenchmarkSpanFrontier/100k-12             257845              4397 ns/op             592 B/op         12 allocs/op
PASS
ok      github.com/cockroachdb/cockroach/pkg/util/span  7.623s
```

the poor performance caused by the interface design by github.com/biogo/store/interval we are using, I will improve it base on the origin version.

**Comment by GregoryIan** [comment]
Looking forward to this optimization very much.

**Comment by amyangfei** [comment]
Thanks @july2993 for great job!
