### ISSUE TITLE
`drop index if exists` is not compatible with MySQL

### ISSUE THREAD

**Issue by glkappe** [pingcap/ticdc#3004]
### What did you do?

A compatibility issue

1. 
Synchronization link：
mysqlA - dm - tidb - ticdc - mysqlB

Execute drop table in mysqlA, and dm will rewrite it as drop table if exitits. When this ddl is synchronized to mysql via ticdc, a syntax unsupported error occurs, resulting in business termination

2. 
tidb - ticdc - mysqlC

Execute drop table if exitits in tidb. When this ddl is synchronized to mysql via ticdc, a syntax unsupported error occurs, resulting in business termination

PS：
In the data synchronization tool, I understand that this problem should not arise, it needs to be considered when it is designed

### What did you expect to see?

changefeed status is normal

### What did you see instead?

changefeed status is stop

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
all version
```
TiCDC version (execute `cdc version`):

```console
all version
```

**Comment by lance6716** [comment]
do you mean DROP INDEX (IF EXISTS)?

**Comment by Win-Man** [comment]
@lance6716 Yes, DROP INDEX(IF EXISTS) will cause this problem.

**Comment by glkappe** [comment]
@sunzhaoyang so if dm does normal synchronization with the upstream `drop table`, there may be no such problem

**Comment by sunzhaoyang** [comment]
@glkappe What is your version of mysql?

**Comment by lance6716** [comment]
adviced by @kennytm , DM could use `/*!80000 if exists */`

in TiDB

```
MySQL [test]> drop index /*!80000 if exists */ idx on t;
Query OK, 0 rows affected, 1 warning (0.001 sec)

MySQL [test]> show warnings;
+-------+------+-------------------------+
| Level | Code | Message                 |
+-------+------+-------------------------+
| Note  | 1091 | index idx doesn't exist |
+-------+------+-------------------------+
1 row in set (0.001 sec)
```

in MySQL

```sql
MySQL [test]> drop index /*!80000 if exists */ idx on t;
ERROR 1091 (42000): Can't DROP 'idx'; check that column/key exists
```

BTW MySQL doc didn't say some version support DROP INDEX IF EXISTS

https://dev.mysql.com/doc/refman/8.0/en/drop-index.html

@leoppro

**Comment by sunzhaoyang** [comment]
It seems that for compatibility, we should not modify the original sql to `if exist`

@lance6716
