### ISSUE TITLE
The Sort-DIR position of log output is incorrect

### ISSUE THREAD

**Issue by glkappe** [pingcap/ticdc#3063]
### What did you do?

1. like this topology，deploy cluster，
![image](https://user-images.githubusercontent.com/21033020/137425777-7aeccdab-6204-4b53-948f-7746f4bb32ca.png)
![image](https://user-images.githubusercontent.com/21033020/137426203-94926889-b9cf-4c01-ad83-592c090ee37c.png)

2. scale out ticdc when i write  `data-dir`, this is also the case
![image](https://user-images.githubusercontent.com/21033020/137426439-cd565e16-5eb4-4dd3-be3b-6307ad751b9f.png)
![image](https://user-images.githubusercontent.com/21033020/137426450-12683352-2026-48c2-a154-9f07c8f861e9.png)
![image](https://user-images.githubusercontent.com/21033020/137426463-0e941187-23e8-486e-87f7-b8df3c45c2dc.png)

### What did you expect to see?

sort-dir the same as data-dir

### What did you see instead?

1. log output `sort-dir` in /tmp/xxx

2. `changefeed create` print `sort-dir` is null in shell. And in log output also.

### Versions of the cluster

tiup-cluster version is v1.6.0
tidb cluster version is v5.0.4

**Comment by overvenus** [comment]
TiCDC validates and adjusts configuration during start, also in previous version TiCDC support per-changefeed sorter-dir (which is deprecated in the lastest release), so we may see inconsistent sort-dir in log.
