### ISSUE TITLE
EtcdWorker ticks too often

### ISSUE THREAD

**Issue by liuzix** [pingcap/ticdc#3112]
### What did you do?

Create 32 changefeeds corresponding to 32 tables. Run the CDC cluster.

### What did you expect to see?

The Etcd server (embedded in PD) would experience a reasonable amount of QPS pressure.

### What did you see instead?

The total QPS to Etcd can be as high as `1000`. It can be higher. The exact quantitative relation with the number of changefeeds is still under investigation.

### Versions of the cluster

v5.1.x, v5.2.x

**Comment by overvenus** [comment]
This issue has been mitigated, change severity to major.

**Comment by asddongmen** [comment]
It Seems that this bug has been solved by #3219 and #3217 , if it happends again, feel free to reopen this issue and @ me.
