### ISSUE TITLE
When the parameter is wrong, cdc.log cannot output the error

### ISSUE THREAD

**Issue by glkappe** [pingcap/ticdc#3133]
### What did you do?

edit-config
```
server_configs:
  cdc:
    log.file.max-size: 300MB
```
reload xx -R cdc

### What did you expect to see?

reload success

### What did you see instead?

screen：
![image](https://user-images.githubusercontent.com/21033020/138702303-523f7ab6-0e96-4d5f-bcbc-1527a60b8751.png)

cdc log output：
none

![image](https://user-images.githubusercontent.com/21033020/138817260-74439710-4408-4a5c-b2b5-edc6f3cce679.png)

run script sh：
![image](https://user-images.githubusercontent.com/21033020/138817156-5fcf9d2f-15d6-4794-9c50-d3151e39c096.png)

### Versions of the cluster

v5.0.4

**Comment by overvenus** [comment]
Fixed by https://github.com/pingcap/ticdc/pull/3520
