### ISSUE TITLE
How to write the `subsystem` field in PR description, to distinguish whether the PR relates to DM or TiCDC

### ISSUE THREAD

**Issue by hi-rustin** [pingcap/ticdc#3195]

**Comment by hi-rustin** [comment]
I propose:
We can introduce `subsystem1,subsystem2([dm/ticdc]): this is commit message` to solve this problem.

If it includes two projects or common files, then it doesn't need to be marked as dm or ticdc, and if only one project is modified then it is marked with parentheses.

cc @lance6716 @gozssky  @amyangfei @overvenus @maxshuang  What do you think?

**Comment by hi-rustin** [comment]
For example:

1. modify  GitHub files: `github: refine the actions file`
2. modify TiCDC sink: `sink(ticdc): add xxx config for MySQL sink`
3. modify DM syncer: `syncer(dm): increase the number of worker`
4. modify TiCDC puller and sink: `puller,sink(ticdc): remove useless code`

**Comment by hi-rustin** [comment]
Or, if the trend across the repository is to merge, then I think we could just close this issue and not specifically differentiate between ticdc and dm, but for now they're still completely different products(and separate from a product perspective later on), and maybe it's necessary to differentiate between these commits.

**Comment by maxshuang** [comment]
> cc: @maxshuang Do you have any thoughts?

Do we have an easy way to force user choose a tag to extract to the title? At first, we can force user to do it manully, but do we have another solution for the next stage? Hope your expert opinion.

**Comment by asddongmen** [comment]
> For example:
> 
> 1. modify  GitHub files: `github: refine the actions file`
> 2. modify TiCDC sink: `sink(ticdc): add xxx config for MySQL sink`
> 3. modify DM syncer: `syncer(dm): increase the number of worker`
> 4. modify TiCDC puller and sink: `puller,sink(ticdc): remove useless code`

There may be multiple files with a same name in different package, shall we add the package name?
for example:
- pipeline/sink
- sink/sink

**Comment by maxshuang** [comment]
> > For example:
> > 
> > 1. modify  GitHub files: `github: refine the actions file`
> > 2. modify TiCDC sink: `sink(ticdc): add xxx config for MySQL sink`
> > 3. modify DM syncer: `syncer(dm): increase the number of worker`
> > 4. modify TiCDC puller and sink: `puller,sink(ticdc): remove useless code`
> 
> There may be multiple files with a same name in different package, shall we add the package name? for example:
> 
> * pipeline/sink
> * sink/sink

I think subsystem is a rough concept, more appropriate to aggregate the pr instead of the detail package name.

**Comment by Ehco1996** [comment]
> For example:
> 
> 1. modify  GitHub files: `github: refine the actions file`
> 2. modify TiCDC sink: `sink(ticdc): add xxx config for MySQL sink`
> 3. modify DM syncer: `syncer(dm): increase the number of worker`
> 4. modify TiCDC puller and sink: `puller,sink(ticdc): remove useless code`

this lgtm, but i am looking forward to the day we don't need to distinguish DM and CDC, so the commit message will look like this:
> mysql-sink: fix xx when xxx
> election: fix master down when xxx

**Comment by lance6716** [comment]
can the bot scan the file changes of the PR, if some file changed under `dm` folder it shall attach an `area/dm` tag?

we can use `-label:area/dm` in search box to exclude the label

**Comment by hi-rustin** [comment]
> can the bot scan the file changes of the PR, if some file changed under `dm` folder it shall attach an `area/dm` tag?
> 
> we can use `-label:area/dm` in search box to exclude the label

It's hard to open GitHub to look at labels when you're troubleshooting a lot of commits locally.

**Comment by hi-rustin** [comment]
For pr and commit we need to focus on local git tool adaptations, not just GitHub.
