### ISSUE TITLE
for `stop-task`, declarative API should wait the task is stoppped

### ISSUE THREAD

**Issue by lance6716** [pingcap/ticdc#3254]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

internally DM should retry and wait the task to stop, when `stop-task`, to implement a declarative API. currently we will return too early when the task has an error 

https://github.com/pingcap/dm/blob/39b5e2098f21260c14373a23069f7e38395d8d7f/dm/master/server.go#L1598-L1625

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lance6716** [comment]
related to unstable CI

https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/241/pipeline/

https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/242/pipeline

**Comment by fatelei** [comment]
let me try

**Comment by lance6716** [comment]
@fatelei do you need our help?

**Comment by fatelei** [comment]
> @fatelei do you need our help?

thanks, currently do need help.
