### ISSUE TITLE
resolved ts is not forward after one TiKV crash

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#330]
1. we start a sysbench task (sysbench oltp_insert --tables=1 --threads=200) and a CDC changefeed
2. the replication works well, at about `2020/03/10 04:28:40.560 -04:00` one TiKV is killed because of OOM. The CDC doesn't receive any region data anymore. (Except for a region_id=8)

Note: has a special tikv config to test frequently region split

```
[coprocessor]

region-max-keys = 3000
region-split-keys = 2500
```

Have some doubts:
1. CDC has almost pulled all changefeed event in time, why TiKV's memory consumes so much.
2. regions seem not quite balance, one store (172.16.5.210) does most work
3. CDC fails to continue replicate after one TiKV crashes.

cdc log: http://139.219.11.38:8000/cDBuP/cdc.log.tar.gz

<img width="628" alt="Screen Shot 2020-03-10 at 16 52 04" src="https://user-images.githubusercontent.com/1527315/76295382-7b168280-62ef-11ea-92b9-21c761edecb8.png">

<img width="1177" alt="Screen Shot 2020-03-10 at 16 55 54" src="https://user-images.githubusercontent.com/1527315/76295686-098b0400-62f0-11ea-8859-a38d515571ef.png">

**Comment by amyangfei** [comment]
leader not balance is caused by storage status. The sequence insert workload leads the region 2 split too fast. Snapshot is not generated completed before the region epoch changes, and it becomes stale.

Increasae `raft-log-gc-size-limit' and 'raft-log-gc-tick-interval` to solve this problem.

**Comment by siddontang** [comment]
@BusyJay 

can we handle these configs automatically if we find this problem?

**Comment by BusyJay** [comment]
Maybe we can abort snapshot generation in time. So that it can start all over again, which should be small enough to be generated quickly.

**Comment by siddontang** [comment]
how to control aborting in time?

**Comment by BusyJay** [comment]
Like sharing an atomic that is reset when split.

**Comment by siddontang** [comment]
SGTM

**Comment by amyangfei** [comment]
In recent test, we have supported this scenario
