### ISSUE TITLE
DM-worker can't boot up when it's assigned relay and can't connect downstream

### ISSUE THREAD

**Issue by lance6716** [pingcap/ticdc#3344]
### What did you do?

1. start-relay -s source1 worker1
2. start a task of source1
3. kill downstream
4. restart worker1

### What did you expect to see?

worker1 is started and report friendly error

### What did you see instead?

worker1 will exit after a short time

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
5.3.0
```
Upstream MySQL/MariaDB server version:
```console
(paste upstream MySQL/MariaDB server version here)
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
(paste TiDB cluster version here)
```
How did you deploy DM: tiup or manually?
```console
(leave TiUP or manually here)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by XuJianxu** [comment]
Need to Add
Versions of the cluster
DM version (run dmctl -V or dm-worker -V or dm-master -V):
5.3.0
