### ISSUE TITLE
can't list all task when some dm-workers offline

### ISSUE THREAD

**Issue by Ehco1996** [pingcap/ticdc#3348]
### What did you do?

* create source1 and bound to  worker1
* create source2 and bound to  worker2
* start a task1 of source1 and task2 of source2
* kill-worker-2
* query-status

### What did you expect to see?

list two task but one success and one with empty status

### What did you see instead?

```
{
    "result": true,
    "msg": "",
    "tasks": [
        {
            "taskName": "test-1",
            "taskStatus": "Running",
            "sources": [
                "mysql-01"
            ]
        }
    ]
}
```

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
v5.3.0
```
Upstream MySQL/MariaDB server version:
```console
(paste upstream MySQL/MariaDB server version here)
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
(paste TiDB cluster version here)
```
How did you deploy DM: tiup or manually?
```console
(leave TiUP or manually here)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by XuJianxu** [comment]
Need to Add 
Versions of the cluster
DM version (run dmctl -V or dm-worker -V or dm-master -V):
5.3.0

**Comment by lance6716** [comment]
the description of "What did you do" is not same with "What did you see instead?". Did you kill worker1 or worker2?

**Comment by Ehco1996** [comment]
> the description of "What did you do" is not same with "What did you see instead?". Did you kill worker1 or worker2?

i kill the dm-worer-1 witch is handlng `test-1`, so there is no task named `test-1` in query-status response.

the conent of  `What did you see instead?`  is confusing because the config of `task-2`  is not  correctly, so the query-status error is reported

I'll change the description  of this issue
