### ISSUE TITLE
log doesn't contain fail to delete shard DDL infos and lock operations

### ISSUE THREAD

**Issue by lance6716** [pingcap/ticdc#3398]
### Which jobs are flaking?

DM-IT

### Which test(s) are flaking?

shardddl1 - DM-RemoveLock

### Jenkins logs or GitHub Actions link

https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/492/pipeline

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

**Comment by WizardXiao** [comment]
`optimistic` test  seems was  affected by `pessimistic` test, as the log of master just has `wait new ddl info putted into etcd` in `pessimistic`, so maybe we should clear environment before run `optimistic` test.
https://ci2.pingcap.net/blue/rest/organizations/jenkins/pipelines/dm_ghpr_integration_test/runs/673/nodes/150/steps/1200/log/?start=0

**Comment by WizardXiao** [comment]
`optimistic` test seems was affected by `pessimistic` test, as the log of master just has `wait new ddl info putted into etcd` in `pessimistic`, so maybe we should clear environment before run `optimistic` test or we can change the `failpoint loginfo` to distinguish `pessimistic` and `optimistic`.
https://ci2.pingcap.net/blue/rest/organizations/jenkins/pipelines/dm_ghpr_integration_test/runs/673/nodes/150/steps/1200/log/?start=0
