### ISSUE TITLE
Sink write rows doesn't represent the real rows when sink is MQ

### ISSUE THREAD

**Issue by gozssky** [pingcap/ticdc#3431]
### What did you do?

![image](https://user-images.githubusercontent.com/17199941/141424127-9f3ae711-9294-4143-abe1-59ab9bc91717.png)

When sink is MQ,  `txn_batch_size` represents the count of messages instead of the count of rows.

### What did you expect to see?

The metric is accurate when sink is MQ.

### What did you see instead?

The metric is incorrect when sink is MQ.

### Versions of the cluster

master

**Comment by overvenus** [comment]
Fixed by #3609
