### ISSUE TITLE
Upgrade cluster from 4.0.14 to 5.3.0，the stopped changefeed automatically becomes to run

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/ticdc#3473]
### What did you do?

- deploy tidb 4.0.14
- create changefeed: tiup ctl:v4.0.14 cdc changefeed create --pd=http://172.16.4.158:2379 --sink-uri="tidb://root:@172.16.6.47:4000/"  --changefeed-id="mysql-task-1"
- pause this changefeed, make sure it has become stopped status.
- upgrade tidb to 5.3.0
- check changefeed status

### What did you expect to see?

The changefeed is still stopped status.

### What did you see instead?

The changefeed become normal status.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
v4.0.14 -> v5.3.0
```

TiCDC version (execute `cdc version`):

```console
v4.0.14 -> v5.3.0
```

**Comment by hi-rustin** [comment]
I found in my local testing that it's just a task status display issue. It won't really sync data.
