### ISSUE TITLE
Buggy sink returning a checkpoint that is too large can cause flow control to dead-lock

### ISSUE THREAD

**Issue by liuzix** [pingcap/ticdc#3531]
### What did you do?

When a table pipeline is blocked by flow control when waiting for the global checkpoint to reach a DDL commit-ts, a table moving into the processor where the blocked table pipeline is running can cause dead lock. **If the sink is buggy so that it returns a checkpoint that is greater than the argument of `FlushRowChangedEvents`**.

### What did you expect to see?

We do not expect a buggy sink. But even if the sink were buggy, we would not expect to see a deadlock problem.

### What did you see instead?

The table pipeline is deadlocked. And the DDL is executed prematurely.

### Versions of the cluster

TiCDC version (execute `cdc version`):

`f847b331572379527bf37a7f19be20448a74b2c2` on `release-5.3`

**Comment by overvenus** [comment]
Inaccurate checkpoint bug has been fixed.
