### ISSUE TITLE
CDC:ErrLoadTimezone on RHEL 6.8

### ISSUE THREAD

**Issue by liuzix** [pingcap/ticdc#3584]
### What did you do?

Run `cdc server --pd=http://pd-host:2379`.

### What did you expect to see?

Everything to be normal.

### What did you see instead?

`[CDC:ErrLoadTimezone]readlink /etc/localtime: invalid argument`

### Versions of the cluster

TiCDC version (execute `cdc version`):

```console
master
```

**Comment by liuzix** [comment]
Possible cause could be that `/etc/localtime` is not a symbolic link on the system.

**Comment by overvenus** [comment]
Let's follow TiDB's implementation. 
https://github.com/pingcap/tidb/blob/bba5fee1e68de8524379b384de8d48e698ef6519/util/timeutil/time.go#L73-L106

**Comment by asddongmen** [comment]
got
