### ISSUE TITLE
online-ddl default value false causes task replication errors

### ISSUE THREAD

**Issue by sunzhaoyang** [pingcap/ticdc#3632]
### What did you do?

DM was upgraded from version 2.0.1 to 2.0.7 with a new parameter `online-ddl` and a default value of `false`, which led to two problems:

1.  The pt/ghost configuration of existing tasks is invalid after the upgrade, resulting in replication errors
2. To fix the above problem, you need to manually add all the existing configuration files with the value of `online-ddl=true`, which is a lot of work.

If the `online-ddl=true` has no negative impact, is it possible to change the default value to `true`?

### What did you expect to see?

change `online-ddl` default value to `true`

### What did you see instead?

`online-ddl` default value  `false`

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
(paste DM version here, and you must ensure versions of dmctl, DM-worker and DM-master are same)
```
Upstream MySQL/MariaDB server version:
```console
(paste upstream MySQL/MariaDB server version here)
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
(paste TiDB cluster version here)
```
How did you deploy DM: tiup or manually?
```console
(leave TiUP or manually here)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by GMHDBJD** [comment]
The issue is caused by https://github.com/pingcap/dm/issues/2223
But I think set online-ddl default value to true is OK

**Comment by okJiang** [comment]
In 2.0.8, if your `online-ddl-scheme` is set by `pt/gh-ost`, `online-ddl` will be transfer to true.
