### ISSUE TITLE
receive commit event before its corresponding prewrite event

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#454]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

region has `initialized`

- workload: bank2 test

2. What did you expect to see?

3. What did you see instead?

> [2020/04/10 17:14:15.811 +08:00] [INFO] [client.go:728] ["EventFeed disconnected"] [regionID=33477] [span="{\"Start\":\"dIAAAAAAABb/ql8AAAAAAAD5\",\"End\":\"dIAAAAAAABb/ql9ygAAAAAD/ADA0AAAAAAD6\"}"] [checkpoint=415894091628806145] [error="prewrite not match, key: [1110100 10000000 0 0 0 0 0 10110 10101000 1011111 1110010 10000000 0 0 0 0 101 1101 11011010], start-ts: 415894091930271874"] [errorVerbose="prewrite not match, key: [1110100 10000000 0 0 0 0 0 10110 10101000 1011111 1110010 10000000 0 0 0 0 101 1101 11011010], start-ts: 415894091930271874\ngithub.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).singleEventFeed\n\tgithub.com/pingcap/ticdc@/cdc/kv/client.go:1117\ngithub.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).partialRegionFeed\n\tgithub.com/pingcap/ticdc@/cdc/kv/client.go:717\ngithub.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).receiveFromStream.func2\n\tgithub.com/pingcap/ticdc@/cdc/kv/client.go:970\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57\nruntime.goexit\n\truntime/asm_amd64.s:1357"]

cdc log: http://139.219.11.38:8000/141xca/cdc.log.tar.gz

4. Versions of the cluster

```
➜  ./cdc version
Release Version: v4.0.0-rc-9-g70a479c
Git Commit Hash: 70a479cb8107ab8b52b0c915e72c4def3ddda9c3
Git Branch: master
UTC Build Time: 2020-04-10 07:11:03
Go Version: go version go1.13.6 linux/amd64
```

```
➜  ./tikv-server -V
TiKV
Release Version:   4.1.0-alpha
Git Commit Hash:   c3f9fba14b04811e77614bcd50007bad17e251c3
Git Commit Branch: master
UTC Build Time:    2020-04-03 06:59:19
Rust Version:      rustc 1.42.0-nightly (0de96d37f 2019-12-19)
Enable Features:   jemalloc portable sse protobuf-codec
Profile:           dist_release
```

**Comment by 5kbpers** [comment]
Already fixed https://github.com/tikv/tikv/pull/7876

**Comment by 5kbpers** [comment]
Already fixed https://github.com/tikv/tikv/pull/7456
