### ISSUE TITLE
mark table design and mark table operation in MySQL sink

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#472]
## Feature Request

**Is your feature request related to a problem? Please describe:**

This is part of #471 

**Describe the feature you'd like:**

- [x] Design the structure of mark table
- [ ] Add mark table update DML in each transaction in MySQL sink

**Comment by overvenus** [comment]
Discussed offline, feasible mark table schema and DML:
```SQL
-- makr table
CREATE TABLE _cdc_repl_mark_${table_id} 
  ( 
     bucket         INT NOT NULL, 
     replica_id     BIGINT NOT NULL, 
     val            BIGINT DEFAULT 0, 
     PRIMARY KEY (id, cluster_id) 
  ); 

-- DML
INSERT INTO _cdc_repl_mark_${table_id} 
VALUES (?, ?, ?) 
on duplicate KEY
UPDATE val = val + 1 ;
``` 

* `_cdc_repl_mark_${table_id}`, tables and mark tables are n:n, means every table in a changefeed will have a corresponding mark table, so there is a table id suffix in mark table name.
* `bucket` avoids conflicts when there are multiple clients update the same mark table.
* `replica_id` is a unique ID belongs to a cluster in the cycle. It identifies DMLs where it comes from.
* `val` is a place holder, we can update it to make sure there will be some events sent to CDC.

**Comment by overvenus** [comment]
Resolved in https://github.com/pingcap/ticdc/pull/509.
