### ISSUE TITLE
Support mark table subscription in processor

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#473]
## Feature Request

**Is your feature request related to a problem? Please describe:**

This is part of #471 

**Describe the feature you'd like:**

- [x] Provide a switch config for cyclic replication
- [ ] Currently each table that will be replicated in a processor is dispatched from the owner, design and implement the mark table dispatch strategy

**Comment by overvenus** [comment]
Both two tasks are implemented at https://github.com/pingcap/ticdc/pull/509.

**Comment by overvenus** [comment]
Resolved in #509.
