### ISSUE TITLE
Support cyclic traffic filter in MySQL sink

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#474]
## Feature Request

**Is your feature request related to a problem? Please describe:**

This is part of #471

**Describe the feature you'd like:**

- [x] collect changed events from mark table in processor
- [x] before replicating data to downstream, filter changed event that is from inner traffic

**Comment by overvenus** [comment]
Both two tasks are implemented at https://github.com/pingcap/ticdc/pull/509.

**Comment by overvenus** [comment]
Resolved in #509.
