### ISSUE TITLE
TiCDC Timezone error

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/ticdc#493]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
When not use UTC. Some data sync is not correct
2. What did you expect to see?
All data is correct

3. What did you see instead?

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
       master
        ```

    - TiCDC version (execute `cdc version`):

        ```
        master
        ```

**Comment by amyangfei** [comment]
fix in https://github.com/pingcap/ticdc/pull/498
