### ISSUE TITLE
CDC stops working  after TiKV power-off

### ISSUE THREAD

**Issue by 5kbpers** [pingcap/ticdc#522]
## Bug Report

1. What did you do? If possible, provide a recipe for reproducing the error.
Power-off one TiKV node.

2. What did you expect to see?
CDC stops working for two minutes.

3. What did you see instead?
CDC should tolerant such errors.

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        4.0.0-rc.1
        ```

    - TiCDC version (execute `cdc version`):

        ```
        4.0.0-rc.1
        ```

**Comment by amyangfei** [comment]
Fix in https://github.com/pingcap/ticdc/pull/531
