### ISSUE TITLE
CDC use too many memory

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/ticdc#526]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
each table using 10M memory

2. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        master
        ```

    - TiCDC version (execute `cdc version`):

        ```
        master
        ```

**Comment by leoppro** [comment]
fixed
