### ISSUE TITLE
CDC should handler properly after cluster destroy

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/ticdc#527]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
When the TiDB cluster destroys. CDC should work well
2. What did you expect to see?
It works well
3. What did you see instead?
It does not handle properly

**Comment by overvenus** [comment]
Can you elaborate on what you mean "work well"?

**Comment by amyangfei** [comment]
Currently TiCDC stores metadata in PD, which is a strong dependency. The upstream disaster scenario is described in https://github.com/pingcap/ticdc/issues/691.
As we have chosen the ts-map plus flashback way to achieve consistent replication, we don't need TiCDC to work anymore after upstream meets disaster.

**Comment by amyangfei** [comment]
won't fix
