### ISSUE TITLE
ticdc generating timezone error in MariaDB sink

### ISSUE THREAD

**Issue by kolbe** [pingcap/ticdc#558]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

Set up a sink to a MariaDB 10.4 instance.

2. What did you expect to see?

3. What did you see instead?

```
[2020/05/11 22:59:20.333 -07:00] [WARN] [mysql.go:137] ["execute DDL with error, retry later"] [query="create table t2 (id int unsigned not null auto_increment primary key, v varchar(32))"] [error="Error 1298: Unknown or incorrect time zone: 'America/Los_Angeles'"] [errorVerbose="Error 1298: Unknown or incorrect time zone: 'America/Los_Angeles'
github.com/pingcap/errors.AddStack
	github.com/pingcap/errors@v0.11.5-0.20190809092503-95897b64e011/errors.go:174
github.com/pingcap/errors.Trace
	github.com/pingcap/errors@v0.11.5-0.20190809092503-95897b64e011/juju_adaptor.go:15
github.com/pingcap/ticdc/cdc/sink.(*mysqlSink).execDDL
	github.com/pingcap/ticdc/cdc/sink/mysql.go:148
github.com/pingcap/ticdc/cdc/sink.(*mysqlSink).execDDLWithMaxRetries.func1
	github.com/pingcap/ticdc/cdc/sink/mysql.go:128
github.com/pingcap/ticdc/pkg/retry.Run.func1
	github.com/pingcap/ticdc/pkg/retry/retry.go:31
github.com/cenkalti/backoff.RetryNotify
	github.com/cenkalti/backoff@v2.2.1+incompatible/retry.go:37
github.com/cenkalti/backoff.Retry
	github.com/cenkalti/backoff@v2.2.1+incompatible/retry.go:24
github.com/pingcap/ticdc/pkg/retry.Run
	github.com/pingcap/ticdc/pkg/retry/retry.go:30
github.com/pingcap/ticdc/cdc/sink.(*mysqlSink).execDDLWithMaxRetries
	github.com/pingcap/ticdc/cdc/sink/mysql.go:126
github.com/pingcap/ticdc/cdc/sink.(*mysqlSink).EmitDDLEvent
	github.com/pingcap/ticdc/cdc/sink/mysql.go:121
github.com/pingcap/ticdc/cdc.(*changeFeed).handleDDL
	github.com/pingcap/ticdc/cdc/changefeed.go:446
github.com/pingcap/ticdc/cdc.(*Owner).handleDDL
	github.com/pingcap/ticdc/cdc/owner.go:359
github.com/pingcap/ticdc/cdc.(*Owner).run
	github.com/pingcap/ticdc/cdc/owner.go:599
github.com/pingcap/ticdc/cdc.(*Owner).Run
	github.com/pingcap/ticdc/cdc/owner.go:536
github.com/pingcap/ticdc/cdc.(*Server).campaignOwnerLoop
	github.com/pingcap/ticdc/cdc/server.go:167
github.com/pingcap/ticdc/cdc.(*Server).run.func1
	github.com/pingcap/ticdc/cdc/server.go:199
golang.org/x/sync/errgroup.(*Group).Go.func1
	golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57
runtime.goexit
	runtime/asm_amd64.s:1373"]
```

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
tidb_version(): Release Version: v4.0.0-beta.2-428-gce923ac85
Git Commit Hash: ce923ac85d97d2682b3570babd541b5948901799
Git Branch: HEAD
UTC Build Time: 2020-05-11 07:53:46
GoVersion: go1.13.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
        ```

    - TiCDC version (execute `cdc version`):

        ```
Release Version: v4.0.0-rc.1-25-g961d4c8
Git Commit Hash: 961d4c87562ccab8273c6aa220e665664862e9f6
Git Branch: master
UTC Build Time: 2020-05-12 01:55:58
Go Version: go version go1.14 darwin/amd64
        ```

**Comment by leoppro** [comment]
hi kolbe,
please reference to #165, hope it can help you solve the problem.

**Comment by kolbe** [comment]
Yes, I'm aware of how to set up MySQL/MariaDB to recognize named time zones, but why is CDC sending these statements in the first place? There are many situations where timezone tables won't have been populated, and it would be best if CDC didn't unnecessarily add that dependency.

**Comment by leoppro** [comment]
We hope to ensure the consistency of upstream and downstream time zones by TiCDC automatically. If there is a problem with the time zone, TiCDC will report the error as soon as possible.

Otherwise, the problem of inconsistent time zones can easily evolve into a silent error, which will lead to inconsistency of upstream and downstream data, but TiCDC has no way to find this problem out.

**Comment by kolbe** [comment]
Can cdc use a numeric timezone instead of a named one? I.e., why not just set the timezone to '+00:00' on all hosts?

**Comment by leoppro** [comment]
Considering the problem of daylight saving time, the two are not exactly equal.
We have tried to unify the time zone of all machines into UTC, but there are some problems when executing DDL.

For example: 
the upstream TiDB execute this ddl: `create table t(a int primary key, b timestamp default '2020-01-01 10:10:10');`
and TiCDC will receive the DDL query string, and try to execute it in downstream TiDB.
Because the SQL contains timestamp, we have to keep the downstream time zone and upstream consistent

**Comment by kolbe** [comment]
Great example! This makes it clear I have no idea how DDL makes its way from TiDB Server to CDC. Does TiDB Server send the literal DDL directly to CDC? TiDB must store this timestamp default clause of the table definition in UTC, so it seems like ideally it'd *send* the table definition to CDC in UTC. Is that possible?

**Comment by leoppro** [comment]
In the current implementation, TiDB sends the literal DDL to CDC directly. 
It is difficult to send the processed DDL(with timestamp in UTC) to TiCDC currently.

**Comment by kolbe** [comment]
Oh, that's kind of a problem, isn't it? There are various elements in TiDB DDL statements that are not legal in MySQL/MariaDB (auto-random, for example).

Maybe TiCDC needs to detect downstream errors executing DDL statements, pause the sink, and reflect the error via the API so it's possible for the administrator to handle the situation.

**Comment by amyangfei** [comment]
Currently TiCDC has provided
- the `--tz` parameter in cdc server (https://docs.pingcap.com/tidb/stable/manage-ticdc#use-binary)
- and the `time-zone` parameter in sink uri
, which solves any known scenarios. Close this issue now, feel free to reopen it if there still exists problem
