### ISSUE TITLE
optimization for changefeed remove

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#564]
## Feature Request

**Is your feature request related to a problem? Please describe:**

- If `advertise-addr` is not provided and `addr` binds on `0.0.0.0`, `cdc cli changefeed remove` will fail

```
» changefeed remove --changefeed-id abf925e9-2a84-42ac-ac28-9f41ec0b9c95
Error: Post "http://0.0.0.0:8300/capture/owner/admin": EOF
Usage:
  cli changefeed remove [flags]
Flags:
      --changefeed-id string   Replication task (changefeed) ID
  -h, --help                   help for remove
Post "http://0.0.0.0:8300/capture/owner/admin": EOF
```
- If not captures are deployed and `changefeed` is created, we can't use `cdc cli changefeed remove` to remove a `changefeed`

**Comment by overvenus** [comment]
Will be fixed in #570 .
