### ISSUE TITLE
The changefeed in stop statue will not be registered to PD gc safepoint service 

### ISSUE THREAD

**Issue by leoppro** [pingcap/ticdc#603]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
stop a changefeed and wait.
we can see that the gc safe point go over the checkpoint ts of the stopped changefeed

2. What did you expect to see?

3. What did you see instead?

**Comment by amyangfei** [comment]
fixed in https://github.com/pingcap/ticdc/pull/797
