### ISSUE TITLE
Support to more data format in mq sink

### ISSUE THREAD

**Issue by leoppro** [pingcap/ticdc#607]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Support to more data format in mq sink, not only Open Protocol.

- [ ] The old version binlog kafka format [proto](https://github.com/pingcap/tidb-tools/blob/master/tidb-binlog/slave_binlog_proto/proto/binlog.proto)
- [x] The canal format [proto](https://github.com/alibaba/canal/blob/master/protocol/src/main/java/com/alibaba/otter/canal/protocol/EntryProtocol.proto)

**Comment by LittleFall** [comment]
Are there any plans to support the canal-json format?

**Comment by handlerww** [comment]
> Are there any plans to support the canal-json format?

In addition, canal set this by `canal.mq.flatMessage = true`

**Comment by amyangfei** [comment]
We have supported canal-json in https://github.com/pingcap/ticdc/pull/1013 @LittleFall @handlerww

**Comment by amyangfei** [comment]
The old version binlog kafka format will not be supported
