### ISSUE TITLE
Using readlink to parse time zone name will fail with legacy time zone names

### ISSUE THREAD

**Issue by kennytm** [pingcap/ticdc#619]
See https://asktug.com/t/topic/35048 for context.

The user's localtime is linked to `/usr/share/zoneinfo/UTC`, so the extracted name is wrongly determined as `zoneinfo/UTC` rather than just `UTC`.

https://github.com/pingcap/ticdc/blob/2d2c5dbaa01ff59a33dd2cf0d9716e03dc2eee92/pkg/util/tz.go#L42-L46

Instead of `time.LoadLocation` you should just read the file and use [`time.LoadLocationFromTZData`](https://pkg.go.dev/time?tab=doc#LoadLocationFromTZData) 🤷.

**Comment by amyangfei** [comment]
The first parameter of `time.LoadLocationFromTZData` is also a `the IANA Time Zone database-formatted data`, such as `Asia/Shanghai`?

**Comment by kennytm** [comment]
Yes, but that would only be used for `.String()`. 

Alternatively you could split the path into components and concatenate everything after the first `zoneinfo`.

BTW please use `path/filepath` rather than `path`
