### ISSUE TITLE
Add version to CDC gRPC service

### ISSUE THREAD

**Issue by overvenus** [pingcap/ticdc#663]
## Feature Request

**Is your feature request related to a problem? Please describe:**

CDC gRPC service needs a version to identify compatibility issues between TiKV and TiCDC.

**Describe the feature you'd like:**

Add version field to CDC request.

https://github.com/pingcap/kvproto/blob/8037ca08f377c8f041ff4a2bf9a7cdbce5479d9a/proto/cdcpb.proto#L18-L20

**Describe alternatives you've considered:**

Instead of adding a version field we could
* Add a new RPC with a version suffix, eg.  `rpc EventFeedV2() {}`.
* Or check TiKV version recorded in PD. (Note: the version bumps after all tikv has been upgraded)

**Teachability, Documentation, Adoption, Migration Strategy:**

N/A

**Comment by amyangfei** [comment]
have supported
