### ISSUE TITLE
Support a status mechanism for changefeed

### ISSUE THREAD

**Issue by leoppro** [pingcap/ticdc#664]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Various errors may be encountered during the execution of replication tasks (e.g. downstream link failure, incompatible DDLs, etc.). we hope to provide a mechanism so that users can quickly understand the status of the current replication task (normal or abnormal), and the reason for the error.

**Describe the feature you'd like:**

- [x] Add a status mechanism to TiCDC's Changefeed to store the sync status in the PD.
- [x] Easily query the status of the changefeed and error messages by `cdc cli`.

**Comment by amyangfei** [comment]
- Add a status mechanism to TiCDC's Changefeed to store the sync status in the PD.
  https://github.com/pingcap/ticdc/pull/689
- Easily query the status of the changefeed and error messages by cdc cli.
 https://github.com/pingcap/ticdc/pull/705, https://github.com/pingcap/ticdc/pull/721

**Comment by amyangfei** [comment]
This feature is supported
