### ISSUE TITLE
Sync data to Apache Pulsar on TiCDC sink module

### ISSUE THREAD

**Issue by wolfstudy** [pingcap/ticdc#681]
## Feature Request

**Is your feature request related to a problem? Please describe:**

https://asktug.com/t/topic/35535

**Describe the feature you'd like:**

![image](https://user-images.githubusercontent.com/20965307/85265267-9c693c00-b4a4-11ea-98e0-73f8438dbcde.png)

The TiCDC sink module currently supports TiCDC Open Protocol output to Kafka, which can implement three consistency guarantees: row-level ordering, final consistency, or strict transaction consistency.

It would be great if we can also consider integrating [Apache Pulsar](https://pulsar.apache.org/en/)

**TODO list**

- [ ] implement Apache Pulsar encoder in TiCDC sink module

### Value description 

This feature will enrich usage scenario in third-party ecosystem

### Value score 

* (TBD) / 4

### Workload estimation 

* (TBD)

**Comment by overvenus** [comment]
Hi @wolfstudy, it would be nice if TiCDC supports Apache Pulsar.

Could you send us a PR to support it?  

To support Apache Pulsar, we need to implement a client which sends Open Protocol messages to Apach Pulsar, you can refer to the Kafka sink implementation at https://github.com/pingcap/ticdc/tree/acd4182cce85ab16d7b3f1cad8aab0908e1f78b9/cdc/sink/mqProducer

**Comment by wolfstudy** [comment]
> Hi @wolfstudy, it would be nice if TiCDC supports Apache Pulsar.

Good news!

> Could you send us a PR to support it?

haha, Sure. If time ok, I will be happy to implement this function. If the friends of the TiDB community and the Apache Pulsar community are interested in this feature, they are also welcome to contribute.

> To support Apache Pulsar, we need to implement a client which sends Open Protocol messages to Apach Pulsar, you can refer to the Kafka sink implementation at https://github.com/pingcap/ticdc/tree/acd4182cce85ab16d7b3f1cad8aab0908e1f78b9/cdc/sink/mqProducer

Currently, Apache Pulsar supports Go language clients, reference to https://github.com/apache/pulsar-client-go. This may be a good start

**Comment by overvenus** [comment]
FYI, this PR adds the Pulsar sink. https://github.com/pingcap/ticdc/pull/734

**Comment by winkyao** [comment]
Could we close this issue? @overvenus

**Comment by overvenus** [comment]
Sure, it has been implemented in #751, and will soon be released on v4.0.4.
