### ISSUE TITLE
Implement batch reader in file sorter

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#696]
## Feature Request

**Is your feature request related to a problem? Please describe:**

In current file sorter, we store `PolymorphicEvent` into file with gob encoding, in the binary format as follows
```
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|  data length  |    gob encoding data  |  data length  |

```

When reading the next `PolymorphicEvent` from file, we read a 8 bit header first and then read bytes with data length. It is more cache-friendly if we can read in a batch way.

https://github.com/pingcap/ticdc/blob/2e4957e05f10133e117c65c9c9e4595047461bdb/cdc/puller/file_sorter.go#L256-L276

**Describe the feature you'd like:**

- [ ] Implement a batch `PolymorphicEvent` reader in file sorter.

Feel free to any optimization method, either reading more data into memory and parse data with memory cache, or refine the encoding way when we store `PolymorphicEvent` into the file and make it easier to perform batch read.

**Comment by qinggniq** [comment]
Hello, there are two different aspects to understand this issue:
1. Set property buffer threshold for reader,  and it will reduce the call times of syscall `read` and io. Or use `mmap` to reimplement a reader to reduce the call times of syscall and io. These methods are not harmful for exist function signature.
2. Let `readPolymorphicEvent` deal a batch size buffer and  return multiply `PolymorphicEvent`,  it will reduce the call times of `readPolymorphicEvent`, and in the same time, can also set property buffer threshold for reader to reduce the call times of syscall `read` and io. But it will break the current function signature.

What do you think?
