### ISSUE TITLE
How to run integration test ?

### ISSUE THREAD

**Issue by qinggniq** [pingcap/ticdc#711]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
I want to run integration test.
2. What did you expect to see?
Sucess.
3. What did you see instead?
Bash syntax error like:
```bash
run.sh: line 26: syntax error near unexpected token `;'
run.sh: line 26: `        mysql) ;&'
```
and a lot of environment variables which should be set but not documented. The link https://github.com/pingcap/ticdc/blob/master/tests/README.md at CONTRIBUTING.md is 404 NOT FOUND.

**Comment by amyangfei** [comment]
```
run.sh: line 26: syntax error near unexpected token `;'
run.sh: line 26: `        mysql) ;&'
```
oops, this maybe a bash compatibility in macOS, the fallthrough syntax `xx) ;&` works well in bash 4.x, but is not available in bash 3.x

**Comment by qinggniq** [comment]
event I replace it with `;;`, there are still many miss environment variable missed, like $OUTPUT_DIR, if I have not set it,  it will execute `rm -rf /`.

**Comment by amyangfei** [comment]
How did you run test cases?
`$OUTPUT_DIR` is defined in `tests/run.sh`

**Comment by qinggniq** [comment]
```shell
$ cd ticdc/tests/batch_add_table
$ sed -i -e s/;&/;;/g run.sh
$ bash ./run.sh
```

**Comment by amyangfei** [comment]
We will add some instructions about how to run integration test soon.
Basically you should run test cases as following
```
$ make integration_test_build # build binary
$ make integration_test CASE=batch_add_table # run a test case
```

**Comment by amyangfei** [comment]
We have added instruction for running integration test. https://github.com/pingcap/ticdc/blob/master/tests/README.md

Feel free to feedback if you have any problems
