### ISSUE TITLE
ddl event ignore？

### ISSUE THREAD

**Issue by lddlww** [pingcap/ticdc#731]
ticdc version is v4.0.2

data not sync to downstream tidb，but in cdc log i found  ```ddl event ignored``` and  ```execute ddl succeeded```

cdc log：
![image](https://user-images.githubusercontent.com/27006237/86887891-df294600-c12b-11ea-94b1-f1a7b388cea1.png)

what's happend?

**Comment by amyangfei** [comment]
Consultion: the ddl event is ignored, but the latter log `Execute DDL succeed` will be logged if the DDL is successfully executed or ignored. It is confused, we will refine this log.

**Comment by lddlww** [comment]
@amyangfei  
how to sync ddl event?

**Comment by amyangfei** [comment]
The DDL is replicated by default. Could you please show the changefeed config?

**Comment by lddlww** [comment]
only follow content：
vim /root/cdc.toml
```
case-sensitive = true
  
[filter]
ignore-txn-start-ts = []
rules = ['br.*','test.*','mysql.*','tiup.*']

[mounter]
worker-num = 16

```
exec：
```
 tiup cdc cli changefeed create --pd http://10.5.17.97:2379 --sink-uri="mysql://root:@10.5.17.97:4001" --config /root/cdc.toml
```

**Comment by amyangfei** [comment]
The table is created under schema `tidb` and `tidb` is not contained in filter.rules, so the DDL is ignored.

**Comment by lddlww** [comment]
filter.rules mean：sync ?

**Comment by amyangfei** [comment]
https://github.com/pingcap/ticdc/blob/21a51d203347c95441ac11c7e8193b56de4dd2b8/cmd/changefeed.toml#L14-L18
like allow/block list

**Comment by lddlww** [comment]
oh thanks，i see

**Comment by lddlww** [comment]
i found dml operator not recorded in cdc log？

**Comment by amyangfei** [comment]
`dml event` is only logged in devel level

**Comment by lddlww** [comment]
@amyangfei  thanks for your patience
it's work now，and i am closing this issue

**Comment by 311ybb** [comment]
> The DDL is replicated by default. Could you please show the changefeed config?

does cdc have event filter  ,so i can ignore some DDL, like drop/truncate?

**Comment by amyangfei** [comment]
> > The DDL is replicated by default. Could you please show the changefeed config?
> 
> does cdc have event filter ,so i can ignore some DDL, like drop/truncate?

There is no so far
