### ISSUE TITLE
Add a new sink to external storage

### ISSUE THREAD

**Issue by 3pointer** [pingcap/ticdc#768]
## Feature Request

**Is your feature request related to a problem? Please describe:**
https://github.com/pingcap/br/issues/325 need TiCDC has the ability to record KV changes to external storage like S3 and Localfile

**Describe the feature you'd like:**
Add new sink to external storage. and according to some users' requirements, S3 is needed. so we should implement new sink to S3 first.

**Describe alternatives you've considered:**

1. Consider Rollback DML, we need old value feature.
2. Define specify message proto, for example, we can define bucket or file name as `DB`.`Table`, the detail content may looks like

|  start_ts  | commit_ts  | event_type  | redo KV change(SQL) | undo KV change | 
|  ----  | ----  |  ----  | ----  | ---- |
| t1  | t2 | DML  | add `key1` `value1` ( insert into `table1`) | remove `key1` |
| t3  | t4 | DDL  | alter table `table1` add column | not support|

3. To keep consistency, only event `commit_ts` < `resolve_ts` should be record.

**Teachability, Documentation, Adoption, Migration Strategy:**

## Workload estimation(person-day)

* Design: 2
* Develop: 4
* QA: 3
* Document: 3

**Comment by IANTHEREAL** [comment]
duplicate with https://github.com/pingcap/ticdc/issues/655

**Comment by DanielZhangQD** [comment]
@3pointer Justo to confirm some info:

1. No plan for gcs now, right?
2. This only supports from v5.0 or will it be cherry-picked to v4.0?

**Comment by 3pointer** [comment]
> @3pointer Justo to confirm some info:
> 
> 1. No plan for gcs now, right?
> 2. This only supports from v5.0 or will it be cherry-picked to v4.0?

1. No, Currently we only support s3 and local shared file system.
2. It will be merge into release-4.0, but it will GA in 5.0
