### ISSUE TITLE
Refine index KV operation

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#774]
## Feature Request

**Is your feature request related to a problem? Please describe:**

This issue is related to https://github.com/pingcap/ticdc/issues/772. Currently if a table has multiple unique indexes, one `delete` DML SQL will generate multiple index KV events in TiKV, and TiCDC will generate multiple `delete` DMLs to downstream.

**Describe the feature you'd like:**

- [ ] Decide whether we can prune delete KV events on part for columns.

**Comment by leoppro** [comment]
already fixed
