### ISSUE TITLE
Support pingcap/errors error code

### ISSUE THREAD

**Issue by overvenus** [pingcap/ticdc#806]
## Feature Request

**Is your feature request related to a problem? Please describe:**

In order to support TiDB error code [RFC](https://github.com/pingcap/tidb/blob/1e7454c81d1f4fae464e835d1a4023a911cfa87b/docs/design/2020-05-08-standardize-error-codes-and-messages.md), we should standardize TiCDC error usage with pingcap/errors Error.

TiCDC should use the scaffold provided by https://github.com/pingcap/errors/pull/21 .

**Describe the feature you'd like:**

Support pingcap errors error code.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

## Workload estimation(person-day)

* Design: 2
* Develop: 2
* QA: 2
* Document: 2

**Comment by amyangfei** [comment]
What we should do
1. Define error classes in TiCDC: `Class` is used to classify which TiCDC internal component does the error belong to.
2. Define the error list in TiCDC, each error contains the following fields. The error is defined via `Build` API of a Builder.
   - `code`, required
   - `codeText`, internal used, required
   - `message`, required
   - `workaround`
   - `Description`
3. How to use the new error system
   - Everywhere we first generate an error in TiCDC, use one of the error defined in step-2 and generates a new error object via API such as `GenWithStackByArgs`
   - When we invoke a third party function and get an error, we have two choices to handle the error
      - Keep the error message from the third party function and create a related error instance in our new error system.
      - Create a new Error instance, and save the third party error in its some field of the new error instance. But this is not implemented in `pingcap/errors` now.
   - If the error information returned from the inner function is enough for the current function to describe the error scenario, then it returns `errors.Trace(err)` or `err` directly to the upper code stack.

**Comment by amyangfei** [comment]
have supported
