### ISSUE TITLE
using batch replace in mysql sink

### ISSUE THREAD

**Issue by leoppro** [pingcap/ticdc#807]
this suggest is from @tshqin

In the current implementation, TiCDC generate SQL for every change event like this:
```
REPLACE INTO `table1`(a,b) VALUES (1,2);
REPLACE INTO `table1`(a,b) VALUES (2,3);
REPLACE INTO `table1`(a,b) VALUES (3,4);
```

In practice, we find that the batch replace has higher performance in TiDB:
```
REPLACE INTO `table` (a,b) VALUES (1,2),(2,3),(3,4);
```
Based on experience, 200-300 rows per batch will show higher performance.

- [ ] using batch replace in MySQL sink

**Comment by tshqin** [comment]
LGTM
