### ISSUE TITLE
changefeed initialization error caused the owner to exit

### ISSUE THREAD

**Issue by aytrack** [pingcap/ticdc#812]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
    1.  create a changefeed using Kafka sink 
    2. stop the Kafka server 
2. What did you expect to see?
    changefeed initialization error will not cause the owner to exit
3. What did you see instead?
    changefeed initialization error caused the owner to exit

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        (paste TiDB cluster version here)
        ```

    - TiCDC version (execute `cdc version`):

        ```
        Release Version: v4.0.3
        Git Commit Hash: 453c96ce0b9e82a62e415672fbfc4c117c898940
        Git Branch: heads/refs/tags/v4.0.3
        UTC Build Time: 2020-07-24 13:05:26
        Go Version: go version go1.13 linux/amd64

        ```

**Comment by amyangfei** [comment]
duplicated with https://github.com/pingcap/ticdc/issues/811

**Comment by amyangfei** [comment]
Fixed in https://github.com/pingcap/ticdc/pull/815
