### ISSUE TITLE
After CDC restart, the changefeed checkpoint lag increasing largely.

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/ticdc#828]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
Restert CDC

2. What did you expect to see?
checkpoint lag stay low.

3. What did you see instead?
![image](https://user-images.githubusercontent.com/17380469/89614399-eff9e280-d8b6-11ea-980c-9d7db7f27c6c.png)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        (master)
        ```

    - TiCDC version (execute `cdc version`):

        ```
        (master)
        ```

**Comment by overvenus** [comment]
The lag is caused by initial incremental scans. It may take a few times when there is a large number of regions in cluster.
