### ISSUE TITLE
Optimization for Grafana metrics

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#868]
## Feature Request

**Is your feature request related to a problem? Please describe:**

CDC metrics are changefeed and capture oriented, but changefeed could be removed and reconstruct, some residual metrics could make monitor confused

**Describe the feature you'd like:**

We should make the monitor more readability and easier to use, some possible solutions

- refine Grafana query expression
- or should we remove some unnecessary metrics when changefeed is removed

**Comment by aytrack** [comment]
After encountered an error `The CRTs of event is not expected, please report a bug` and the changefeed stopped  with `"message": "can not found schema snapshot, ts: 419043456504299522"`, `checkpoint_ts_lag` wrote a large values 
```
ticdc_processor_checkpoint_ts_lag{capture="172.16.4.83:8310",changefeed="mysql-sink"} 1.598525505251e+09
```
![image](https://user-images.githubusercontent.com/10184437/91516163-5bb2f680-e91d-11ea-86a9-6134dfae5031.png)
The detail test process: [cdc_test](https://docs.google.com/document/d/1TbTsybv-TqS5qdI2fPE3Ceq44Eo7WiNmWLV5h3bX0dw/edit#bookmark=id.4trxmglmsqtr)

**Comment by aytrack** [comment]
Some panel need to remove
![image](https://user-images.githubusercontent.com/10184437/92068690-28b7a980-edda-11ea-8722-e5ff8be44b1e.png)

**Comment by amyangfei** [comment]
metric has been fixed or outdated
