### ISSUE TITLE
Potential table resolved_ts regression

### ISSUE THREAD

**Issue by MyonKeminta** [pingcap/ticdc#873]
## Bug Report

We know that sometimes a region's resolved_ts may regress when reconnecting, but a table's resolved_ts is not expected to regress. However, there are some cases that it may happen, which can potentially cause fatal error "The CRTs must be greater than the resolvedTs".

### Case 1

Suppose region 1's range is ["A", "C"), region 2 ["C", "D"), table T's range starts from "C". So region 2 is the left-most region of table T. **There's an uncommitted lock on key "B" (lock_ts = 90) in region 1.**
Then, suppose "split on table" is not enabled or random-merge is enabled, then region1 and region2 may happen.
Then it's possible:

1. CDC captures table T1, the table's resolved ts is 100, region2's resolved_ts is 100
2. Region 1 merges into region 2 produces region 2'
3. CDC reconnects region 2 with checkpointTs = 100
4. TiKV scans region 2 and found lock "B" whose ts is 90
5. Region 2 initialized in TiKV with resolved_ts = 90
6 TiKV sends message resolved_ts=90 to CDC, which is smaller than the table's current resolved ts 100

### Case 2

Suppose CDC is capturing table 1 (resolved_ts = 100) which includes region 1 (resolved_ts = 100)

1. A new transaction writes lock (ts = 90) to region 1
2. Region 1's leader changes
3. CDC reconnects region 1 with checkpointTs = 100
4. TiKV scans region 1 and found a lock whose ts is 90
5. Region 1 initialized with resolved_ts = 90 and sends it to CDC.

**Comment by leoppro** [comment]
fixed in https://github.com/pingcap/ticdc/pull/935
