### ISSUE TITLE
Support clustered index in TiCDC

### ISSUE THREAD

**Issue by amyangfei** [pingcap/ticdc#919]
## Feature Request

**Is your feature request related to a problem? Please describe:**

TiDB implements clustered index in 5.0, ref: pingcap/tidb#17044, TiCDC is not compatible with clustered index now

such as when decode a row key-value, the handle ID is treated as int64.

https://github.com/pingcap/ticdc/blob/01c2087b5b314587c416cfdd5bb315589a28adef/cdc/entry/codec.go#L108

**Describe the feature you'd like:**

Support clustered index in TiCDC

### Time

GanttStart: 2020-09-15
GanttDue: 2020-10-30
GanttProgress: 0%

## Workload estimation(person-day)

* Develop & QA: 10
* Document: 1

**Comment by overvenus** [comment]
@coocood PTAL, could you assign someone to fix the bug?
