### ISSUE TITLE
ticdc 只能访问本机，不能在别的机器执行

### ISSUE THREAD

**Issue by foxchenlei** [pingcap/ticdc#930]
**前提：**
ticdc 4.0.5
centos7
**问题描述**
ticdc 命令查询操作只能在ticdc部署的机器执行，开起来是源码默认指定localhost了.
![image](https://user-images.githubusercontent.com/17720133/92355363-a4855f00-f116-11ea-8005-16f7dcc9bd0b.png)

**期望：**
我想在任一机器执行ticdc 查询命令，或者加个参数 能指定cdc 的ip地址

**Comment by leoppro** [comment]
麻烦执行一下 `./cdc cli capture list --pd=xx` 截个图

**Comment by foxchenlei** [comment]
我的cdc 是binary，在A机器。 ticdc 部署 在B机器。 所以A机器ps 是看不到。 希望能使用cdc 的binary 在任一机器 指定ticdc的地址实现管理
![135486375cbbc73afad33839bf1171c](https://user-images.githubusercontent.com/17720133/92366016-2f6e5580-f127-11ea-8251-57d1ab750a58.png)

![ebdf399206a71750816a5b2f0467d01](https://user-images.githubusercontent.com/17720133/92366162-5d539a00-f127-11ea-8eb9-6763f0de407d.png)

**Comment by leoppro** [comment]
对 我知道，cdc是可以实现远程管理的。我估计是你B机器的启动参数配错了。
你在 B 机器上 执行 `ps aux | grep cdc` 我看一眼你 cdc server 的启动参数。

另外执行`./cdc cli capture list --pd=xx` 可以佐证我的推测，你上面截的两个图都不是`capture list `哈

**Comment by foxchenlei** [comment]
# ps -ef|grep cdc
root     356255 356113  0 16:34 pts/0    00:00:00 grep --color=auto cdc
root     391993 391570 16 Sep03 ?        16:46:48 /cdc server --pd=http://xxxx:2479 --log-file=/data/ticdc.log --advertise-addr=:8300 --addr=0.0.0.0:8300 --tz=Asia/Shanghai

**Comment by foxchenlei** [comment]
是我监听端口配置错了吧--advertise-addr=:8300

**Comment by leoppro** [comment]
这个cdc server 是如何启动的呢？是手动启动的还是 tiup 启动呢？
--advertise-addr=:8300 这个启动参数是有问题的

**Comment by leoppro** [comment]
是的 --advertise-addr=:8300 要配置本机ip:port

**Comment by foxchenlei** [comment]
我手动配错了，谢谢回答
